### ISSUE TITLE
modificare test rhw700 in rhw850

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#100]
L'attuale dissemina IFS al momento non ha i dati necessari a questo prodotto a 750hPa e credo sia per questo che i build stanno fallendo: https://simc.arpae.it/moncic-ci/arkimaps/last/master/fedora34/build.log

Spostando tutto a 850hPa (prodotto rhw850) dovrebbe funzionare (a questo livello i dati ci sono sia per COSMO che per IFS)

**Comment by spanezz** [comment]
Investigando, il problema in quel test mi sembra diverso: per qualche motivo i dati li avrei pure (ci sono in `testdata/rhw700/`), però in `recipes/wind_inputs.yaml` la definizione di `u700` e `v700` nel caso di eccodes è identica per cosmo e ifs.

Quando fa il dispatch nel test, anche se i dati sono di IFS fa match la regola per Cosmo (immagino perché viene prima), e quindi i dati da lí in poi vengono taggati come Cosmo. Il test fallisce perché si aspettava che gli input a Cat fossero di IFS.

Sono pure in realtà dati di IFS, ma sono stati identificati come Cosmo a causa dell'ambiguità nella definizione eccodes di u700 e v700.

È possibile estendere quel match di eccodes per distinguere i modelli?

**Comment by brancomat** [comment]
Dopo ulteriori chiarimenti a voce con @spanezz, il problema non è nel test specifico ma su alcuni match ambigui delle regole di eccodes. Ho aperto sul tema specifico la #101, chiudo questa.
