### ISSUE TITLE
mostrare (alcuni?) commenti dello yaml delle ricette nei file md di documentazione

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#102]
Emerso da #5 :
si potrebbe implementare un modo per avere commenti nello YAML che vengono mostrati anche nella documentazione della ricetta, in modo da renderli piú fruibili.

(a bassa priorità)

**Comment by spanezz** [comment]
Proposta implementativa: aggiungere la chiave 'notes' nella recipe e negli input, opzionale, che copi il testo in una sezione "Note" nel markdown della documentazione

**Comment by spanezz** [comment]
Implementato come prototipo. Si può aggiungere `notes:` alla ricetta (allo stesso livello di `description:`) o ai singoli input (allo stesso livello di `model:`) e dovrebbero venire propagati nella documentazione.

Passo la palla per provarlo, non appena ci sia la necessità di annotare una ricetta con qualcosa che debba finire nella sua documentazione
