### ISSUE TITLE
Rendering: indice K

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#106]
Calcolo del K-index:
```
t850 - t500 + td850 - (t700 - td700)
```
(temperature in Celsius)

**Comment by spanezz** [comment]
Manca il nome, la chiamerò per il momento `kindex`

**Comment by spanezz** [comment]
Abbiamo le `t` ma non le `td`.

Peccato, sembrava un buon banco di prova per il nuovo tipo di input `expr`

**Comment by brancomat** [comment]
è andata! grazie a entrambi
