### ISSUE TITLE
Rendering: theta-e

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#108]

**Comment by dcesari** [comment]
Non so se può servire, ma la temperatura potenziale equivalente è tra le variabili calcolabili da libsim, con `--output-variable-list=B12193`. Richiede in ingresso temperatura, pressione e umidità in qualche forma (RH, Td, q, da verificare che tutte le possibilità funzionino).

**Comment by brancomat** [comment]
per COSMO: calcolare Theta-e alla 925hPa secondo metodologia segnalata da @dcesari (grazie)

solo per IFS vengono già fornite al livello 2PV Theta-e e vento a cui va aggiunto al plot (specifico di IFS) la mslp

**Comment by spanezz** [comment]
Per modellare "l'umidità in qualche forma" c'è ora l'input type [`or`](https://github.com/ARPA-SIMC/arkimaps/blob/master/doc/INPUTS.rst#or) che prende il primo che trova tra quelli elencati.

Caveat: il match è fatto per step, quindi potrebbe essere che se si fa un or di `[rh, td, q]`, alcuni step siano calcolati con `rh` e altri con `td` perché `rh` non c'era.
