### ISSUE TITLE
Stabilire valori sensati di `--comp-frac-valid` per medie e aggregazioni

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#112]
Cito @dcesari:

Aggiungo una nota sul `--comp-frac-valid=0`, metterlo a 0 è un po' azzardato, l'avevo proposto come soluzione rapida all'inizio, perché potrebbe darti una media valida anche se c'è un solo valore buono nell'intervallo. Ora la formula legata a quell'argomento è un po' complicata nel caso di elaborazioni istantanee->medie (astrologata da @pat1) 

```
      --comp-frac-valid=REAL
              (from  0.  to 1.) specify the fraction of input data that has to
              be valid in order to consider a  statistically  processed  value
              acceptable;  for instantaneous data the criterion is the longest
              time between two contiguous valid data within comp-step interval
              following  this rule: longest=comp-step/(comp-frac-valid*999 +1)
              thus comp-frac-valid == 0 => longest=comp-step,  comp-frac-valid
              == 1 => longest=comp-step/1000) [default=1.00000000]
```
comunque diciamo che se poniamo ad es. `--comp-frac-valid=0.003` ne consegue che la media è valida se i dati distano al max `comp-step`/4 circa cioè 6 ore nel nostro caso.

_Originally posted by @dcesari in https://github.com/ARPA-SIMC/arkimaps/issues/109#issuecomment-1085994640_

**Comment by brancomat** [comment]
Sono d'accordo con Davide per hardcodare una scelta sensata.

Questa direi sia divisa in due task: la scelta dei valori la approfondisco con @dcesari, poi nel caso sia consigliabile avere valori separati a seconda del tipo di operazione entra in gioco @spanezz  (perché al momento mi pare che `--comp-frac-valid` sia unico per tutte le tipologie di vg6dtrasformazioni)

**Comment by spanezz** [comment]
In `arkimapslib/inputs.py`, se guardate in `Decumulate` e `Average` c'è un parametro `args`: potete provare a spostare `"--comp-frac-valid=…"` dal corpo di `VG6DStatProcMixin.generate` a quegli `args` e sperimentare coi valori che preferite per `Decumulate` e `Average`.

Come vedete è astratto a tal punto che ci vuole niente, se necessario, a rendere configurabile `args` anche da ricetta, o a fare un input generico di rielaborazione statistica con `vg6d_transform` al quale passare parametri arbitrari

**Comment by spanezz** [comment]
Ora ho messo possibile specificare `comp_stat_proc` e `comp_frac_valid` nella definizione dell'input.

`comp_stat_proc` ha valore `1` o `254:0` a seconda se Decumulate o Average. `comp_frac_valid` ha default `0` in tutti i casi.

Se trovate un default migliore di 0, ditemelo che lo cambio in arkimaps invece di doverlo mettere in tutte le ricette.

**Comment by spanezz** [comment]
Questa è una minuzia ignorabile, però se trovate nomi migliori per quei parametri, volentieri, cosí, non inchiavardiamo i parametri di `vg6d_transform` nell'API degli input, metti che un giorno decumuliamo in modo diverso.

**Comment by brancomat** [comment]
Da una ricognizione interna, praticamente tutte le procedure operative che lavorano su dati previsti usano `--comp-frac-valid=0`.
Può aver senso tararlo diversamente ma è un'operazione che andrebbe fatta in maniera coordinata su tutte le procedure per garantire output consistenti, in altre parole, non è una issue di arkimaps, la chiudo, eventualmente cambiamo il default.

I nomi dei parametri in questo caso specifico non proverei a generalizzarli, sono un molto libsim-specifici e in un ipotetico cambio di backend di cumulazione non è detto siano presenti o facilmente traducibili.
