### ISSUE TITLE
come specificare postprocessing comuni per gruppi di modelli diversi

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#118]
Premesso che probabilmente mi sto perdendo in un bicchier d'acqua, ma:

Caso 1 (semplice): modelli a input singolo diverso e postprocessing comune a tutti.
Questo funziona, ad esempio qui: 
https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/tp_inputs.yaml

Caso 2 (complesso): modelli che hanno input diversi e un postprocessing da applicare solo ad un subset di di modelli.
Ho tentato un'implementazione (che però manda in crisi i test) qui:
https://github.com/ARPA-SIMC/arkimaps/blob/2851dcd08ca77bd69fbf72f2dc584a6c1799172b/recipes/sf_inputs.yaml

Ma ha una serie di problemi (`snowsum` e `snowcosmo` vengono giustamente prodotti due volte visto che gli input ci sono).
Quale sarebbe il modo migliore di procedere?
1) Potrei diversificare i nomi dei sottoprodotti per modello (tipo `snowsum_cosmo`, `snowsum_icon`, eccetera) ma va un po' a scapito della leggibilità
2) Potrei rinominare il model dei postprocessamenti comuni in un generico "icon-cosmo" e tenerne uno solo per tipologia, questo però implicherebbe che non ho più continuità fra il model delle variabili di partenza e quello dei prodotti intermedi, che va un po' contro quanto ci si era detti nella #114 
3) Altro (specificare)

**Comment by spanezz** [comment]
Non ho capito bene il comportamento richiesto nel caso 2. Quello che ho capito:
* hai un postprocessing che vuoi far girare solo per gli input di alcuni modelli (tipo `snowcosmo`)
* hai dati di input sia per cosmo che per icon, per cui lui ti postprocessa per entrambi
* vuoi evitare la doppia postprocessazione se te ne serve uno solo

Se questa è la questione, si potrebbe pensare a dire "genera snowdec1 solo per un modello, il primo che trovi". Al momento, se ci sono input per cosmo e per icon, immagnio lui generi uno snowdec1 per entrambi (e poi non so quale scelga per il rendering)

**Comment by brancomat** [comment]
A seguito di telefonata con @spanezz ho revisionato la ricetta https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/sf_inputs.yaml, l'approccio (applicato lì) è usare il type `or` per selezionare gli output intermedi in modo che l'output dato in pasto all'ultimo postprocessing sia unico.

Al momento restano scoperti i test che falliscono e sono da aggiornare, lascio aperta la issue come promemoria.
