### ISSUE TITLE
benchmark su tiles

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#126]
Indagare se esistono differenze sensibili fra produrre X tiles singolarmente e un quadratone più grande (8x8? 4x4?) da ritagliare.

La strategia più semplice potrebbe essere creare un flavour tile ad hoc, e tramite dispatch+display generare un .py di creazione tiles su cui fare gli esperimenti del caso.

**Comment by spanezz** [comment]
Ho una specie di deja-vu come se l'avessimo già fatto, ma non mi ricordo piú come, quando, e cosa ne venne fuori. Questo giro almeno abbiamo un ticket e lo possiamo documentare qui.

Ho provato con 
[testcase.zip](https://github.com/ARPA-SIMC/arkimaps/files/10149074/testcase.zip).

I tempi sono pure promettenti:
```
$ monci run -w. arkimaps time ./render.py 
0.36user 0.33system 0:00.70elapsed 99%CPU (0avgtext+0avgdata 93456maxresident)k
270232inputs+80outputs (225major+13445minor)pagefaults 0swaps
$ monci run -w. arkimaps time ./render.py 1
0.43user 0.37system 0:00.89elapsed 90%CPU (0avgtext+0avgdata 93608maxresident)k
270232inputs+144outputs (226major+13879minor)pagefaults 0swaps
$ monci run -w. arkimaps time ./render.py 2
0.56user 0.31system 0:00.88elapsed 100%CPU (0avgtext+0avgdata 97104maxresident)k
270232inputs+584outputs (226major+15546minor)pagefaults 0swaps
```

Però, bizzarramente, il contouring renderizzato è simile ma non coincide.

Per realizzare quel test case, ho preso il `.py` generato per la prima tile di un livello di zoom inferiore, e a seconda di `step_up`  ho sostituito con l'mmap della prima tile dei livelli di zoom superiore, aumentando `output_width` di conseguenza. Può essere pure che sia un'approssimazione sbagliata e ci fosse altro da mettere a punto (però , come può essere che vada bene cosí e le differenze nel contouring non siano sostanziali.

Provate un po' anche voi?

**Comment by brancomat** [comment]
Fatte un po' di prove, il contouring renderizzato è diverso perché aggiustando solo l'output width senza ripercuotere il cambiamento su i vari `*_[x,y]_length` di fatto Magics abbassa la risoluzione del contouring.

Sistemando la cosa (nuovo testcase: [testcase_v2.zip](https://github.com/ARPA-SIMC/arkimaps/files/10308337/testcase_v2.zip)) i contouring diventano coincidenti (tranne la distribuzione delle label che non è fondamentale) e i tempi (e l'uso di ram) pur peggiorando restano comunque promettenti :

testcase originale:
```
$ /usr/bin/time python3 render.py
0.56user 0.05system 0:00.60elapsed 102%CPU (0avgtext+0avgdata 114400maxresident)k
0inputs+64outputs (0major+17001minor)pagefaults 0swaps
$ /usr/bin/time python3 render.py 1
0.66user 0.07system 0:00.67elapsed 109%CPU (0avgtext+0avgdata 116548maxresident)k
0inputs+272outputs (0major+17978minor)pagefaults 0swaps
$ /usr/bin/time python3 render.py 2
0.71user 0.06system 0:00.72elapsed 106%CPU (0avgtext+0avgdata 119700maxresident)k
0inputs+552outputs (0major+19411minor)pagefaults 0swaps
```

testcase_v2:
```
$ /usr/bin/time python3 render.py
0.55user 0.05system 0:00.58elapsed 102%CPU (0avgtext+0avgdata 113340maxresident)k
0inputs+64outputs (0major+17002minor)pagefaults 0swaps
$ /usr/bin/time python3 render.py 1
0.92user 0.06system 0:00.81elapsed 122%CPU (0avgtext+0avgdata 123460maxresident)k
0inputs+312outputs (0major+19633minor)pagefaults 0swaps
$ /usr/bin/time python3 render.py 2
2.38user 0.08system 0:01.65elapsed 149%CPU (0avgtext+0avgdata 143692maxresident)k
0inputs+776outputs (0major+25790minor)pagefaults 0swaps
```

**Comment by brancomat** [comment]
Commento a margine: se si va per questa strada un'ulteriore ottimizzazione potrebbe essere generare i livelli di zoom contigui creando macrotiles da affettare per il livello di zoom inferiore e usando un resize progressivo per i livelli di zoom superiore.
Questa cosa ha come pro che tutti i contouring sarebbero più ad alta risoluzione (in termini di andamento dei campi) però impatta sulle label (che diventano illegibili).
Esempio con script del testcase con output-2 generato canonicamente (a sx) resizato dal macro-tile (a dx):
![image](https://user-images.githubusercontent.com/13255425/209674659-7c5faa78-4c8e-497b-933d-7546c10948c4.png)

potrebbe aver senso ma solo per i prodotti con contour shading ma non per isolinee (`contour_shade: off`, per cui le label sono fondamentali) e gli indicatori del vento.

**Comment by brancomat** [comment]
Ulteriore nota a margine: utilizzando `svg` come output (basta semplicemente cambiare `output_formats`) il processing è leggermente più spedito ma il plot risultante è decisamente più complicato da gestire come dimensioni:

```
$ /usr/bin/time python3 render_png.py 2
2.37user 0.07system 0:01.58elapsed 154%CPU (0avgtext+0avgdata 143780maxresident)k
0inputs+776outputs (0major+25797minor)pagefaults 0swaps
$ /usr/bin/time python3 render_svg.py 2
2.19user 0.08system 0:01.44elapsed 158%CPU (0avgtext+0avgdata 134820maxresident)k
0inputs+5096outputs (0major+23500minor)pagefaults 0swaps


387K 27 dic 16.52 output-2.png
2,5M 27 dic 16.53 output-2.svg
```

**Comment by brancomat** [comment]
> Parto con quella, e poi a scalare ci pensiamo con calma?

Se l'ipotesi è generare macrotile alla stessa risoluzione attuale (quindi tralasciare per ora il discorso upscaling+resize di [questo commento](https://github.com/ARPA-SIMC/arkimaps/issues/126#issuecomment-1365910943) che in effetti si porta dietro parecchie complicazioni) direi sì.
Aspetterei comunque parere di @edigiacomo sul tema prima di procedere

**Comment by edigiacomo** [comment]
> Se l'ipotesi è generare macrotile alla stessa risoluzione attuale (quindi tralasciare per ora il discorso upscaling+resize di [questo commento](https://github.com/ARPA-SIMC/arkimaps/issues/126#issuecomment-1365910943) che in effetti si porta dietro parecchie complicazioni) direi sì.

Sono d'accordo anche io, grazie!

**Comment by spanezz** [comment]
Ho fatto alcuni push oggi che sistemano un po' di problemi trovati facendo prove.

Una modifica introdotta oggi per semplificare la gestione degli script di render, è che ora sono tutti nella workdir in `renderers/rendererNNN.py`. I nomi riflettono il fatto che, unendo vari prodotti nello stesso script di render, non c'è una corrispondenza tra il nome dello script e quello che renderizza.

Prima gli script venivano hardlinkati a nomi corrispondenti ai prodotti, al momento questo non lo faccio piú.  In teoria, se uno script scoppia, si vede il suo nome nei log e lo si può riprendere per riprodurre lo scoppio. Per altri cose, tipo fare prove per mettere a punto i parametri di render di un prodotto, se vediamo che non è banale trovare lo script corrispondente con qualche semplice grep posso rentrodurre dei symlink, o il nome dello script di render nel json, o altre cose simili per semplificare il compito

**Comment by brancomat** [comment]
> 2\. se fa prima a calcolarlo

Questi log di un run su cosmo_2I_ruc fatto prima su branch `master` poi su `issue126`:

```
master:
        Command being timed: "./cosmo_2I_ruc.sh -le d today 12:00"
	User time (seconds): 9628.10
	System time (seconds): 324.51
	Percent of CPU this job got: 705%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 23:30.92
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 523112
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1857
	Minor (reclaiming a frame) page faults: 55928417
	Voluntary context switches: 355429
	Involuntary context switches: 740632
	Swaps: 0
	File system inputs: 194136
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
	
	
issue126:	
        Command being timed: "./cosmo_2I_ruc.sh -le d today 12:00"
	User time (seconds): 7504.56
	System time (seconds): 61.08
	Percent of CPU this job got: 600%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 20:59.16
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 912108
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 475
	Minor (reclaiming a frame) page faults: 5380052
	Voluntary context switches: 220447
	Involuntary context switches: 771052
	Swaps: 0
	File system inputs: 3832
	File system outputs: 128
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Mi manca ancora però il confronto visivo dei risultati, aggiorno in questa issue appena ho tempo di farlo.

**Comment by brancomat** [comment]
Confronto mappe effettuato, i contouring e le isolinee sono identici, nettissimo miglioramento nel vento, questo con l'attuale master:
![image](https://user-images.githubusercontent.com/13255425/213232406-17bad9dc-52b9-4abd-bfdc-e8dea2eccc56.png)
questo con il branch issue126:
![image](https://user-images.githubusercontent.com/13255425/213232247-ea5672e2-7674-4501-a5fa-6bbdf38c4c6c.png)

agli zoom superiori 8x8 copre tutto il dominio italiano, scendendo si vedono i bordi fra macro-tiles ma restano comunque più che accettabili (e in ogni caso meglio di prima).
Il miglioramento performance del 10% (circa) è un buon bonus, il peggioramento in uso di ram è prevedibile e accettabile.

In sostanza (riporto parere mio e di @edigiacomo) si potrebbe fare merge in master e fare nuova release.
