### ISSUE TITLE
diagnostica problematiche rendering

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#128]
Questo più che un problema è un resoconto ma si porta dietro un paio di domande.
Abbiamo avuto saltuari problemi di blocco delle catene di produzione su un server condiviso. Blocco nel senso che l'operazione di render sembrava non terminare mai.

In un caso che sono riuscito a fotografare la situazione era la seguente:
```
   1955 ?        Ss     0:00 /usr/sbin/crond -n
3675278 ?        S      0:00  \_ /usr/sbin/CROND -n
3675282 ?        Ss     0:00      \_ /bin/bash /home/simdaemon/svn/mappotiles/cosmo_5M_ita.sh -s daily -s archived-model CINECA cosmo_5M_ita -le d today 0:00
3676020 ?        S      0:00          \_ timeout -v 30h bash -c /home/simdaemon/svn/mappotiles/local_arkimaps/arkimaps render --recipes=/tmp/d_test.crontab.salop.mappotiles.cosmo_5M_ita.00.Z850GvRFn3/recipes --flavour ita_small_tiles /tmp
3676021 ?        Sl     7:56              \_ /usr/bin/python3 /home/simdaemon/svn/mappotiles/local_arkimaps/arkimaps render --recipes=/tmp/d_test.crontab.salop.mappotiles.cosmo_5M_ita.00.Z850GvRFn3/recipes --flavour ita_small_tiles /tmp/d
 136527 ?        Z      0:08                  \_ [arkimaps] <defunct>
 136552 ?        Z      0:08                  \_ [arkimaps] <defunct>
 136696 ?        Z      0:06                  \_ [arkimaps] <defunct>
 136730 ?        Z      0:06                  \_ [arkimaps] <defunct>
 136914 ?        Z      0:07                  \_ [arkimaps] <defunct>
 136985 ?        Z      0:04                  \_ [arkimaps] <defunct>
 136987 ?        Z      0:02                  \_ [arkimaps] <defunct>
```
Il file out.tar prodotto fino a quel momento non aveva log e non c'è un'opzione di debug in `arkimaps render`.

In `dmesg` c'erano tracce di processi arkimaps killati per memoria esaurita.

Al di là di un'attività di profiling che ho comunque messo in cantiere per capire come tarare i server su cui gira arkimaps in termini di rapporto fra cpu e ram (la parallelizzazione è basata sul numero di core disponibili, giusto?) mi chiedevo:
1) se c'erano modi più furbi di diagnosticare una situazione del genere
2) se lato arkimaps è "normale" che un sottoprocesso killato da OOM lasci il parent appeso. Provo a rispondermi da solo, se capisco bene  (https://unix.stackexchange.com/questions/631539/is-there-a-way-to-configure-the-linux-oom-killer-to-kill-the-parent-instead-of-c) una soluzione potrebbe essere aggiustare `oom_score_adj` in modo che il parent sia più appetibile per OOM killer dei child (premio Frase Che Avrei Preferito Non Scrivere 2022) però sono campi che conosco molto poco.

**Comment by spanezz** [comment]
Bel colpo, riuscire a trovare una root cause alla situazione!

Al momento i sottoprocessi di arkimaps sono gestiti col modulo standard [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool) di Python, che probabilmente potrebbe fare di piú per gestire i processi che muoiono.

Confermo che il numero di processi è al momento il numero di CPU della macchina.

Tutto questo era il modo piú semplice per far build paralleli in fase di prototipo, e può essere che sia arrivato al suo limite.

La coordinazione tra arkimaps e i suoi worker che fanno rendering è praticamente tutta nel file system: i dati sono nella working directory, la descrizione di un'immagine da generare è una piccola struttura dati serializzabile.

Dato un filesystem condiviso, il rendering può essere fatto da un numero arbitrario di processi, e pure su un numero arbitrario di macchine.

Riprogettiamo la cosa in base a queste premesse?

**Comment by spanezz** [comment]
Riapro il ticket, visto che ci stiamo facendo ricerca sopra

**Comment by spanezz** [comment]
Articolo significativo, grazie @edigiacomo: https://pythonspeed.com/articles/python-multiprocessing/

In teoria, nel processo principale di arkimaps faccio attenzione a non far partire thread, prendere lock, importare magics. però può sempre essere che nella catena di dipendenze di arkimaps ci sia qualcosa che tira su cose, tipo arkimet

**Comment by spanezz** [comment]
Ho pushato nel branch `schedule` un renderer alternativo che sfrutta gli script python di debugging generating durante il rendering, e li chiama direttamente come sottoprocessi per renderizzare.

Al momento è piú lento perché:

* Magics viene importato una volta per PNG, invece di una volta ogni 16 PNG
* Non ho reimplementato lo scheduling su piú core

Però la test suite già passa e ci si possono far sopra prove. In vista di #129, questo rende la distribuzione del rendering lo stesso problema di "un lungo elenco di scriptini da eseguire, anche in parallelo, in una directory"

**Comment by spanezz** [comment]
In 8ff0c963f74bc34347e13ce6ec05ab8ddb2cb664, pushato su master, ho rifatto il sistema di scheduling dei render.

Ora genera script python (gli stessi che possono poi essere usati per debuggare magics) ma con 16 prodotti per script, per caricare Magics una volta sola ogni 16 prodotti.

Gli script Python sono poi lanciati a eseguire in parallelo usando uno scheduler basato su asyncio, che non usa né multiprocessing né i thread.

In vista di #129, in teoria ci basta cambiare lo scheduler con qualunque altra cosa che sia in grado di lanciare qualche centinaio di script e salvarne lo standard output

**Comment by brancomat** [comment]
Questa al momento mi pare risolta
