### ISSUE TITLE
Invio di log, licenza e altre informazioni nell'output del postprocessatore

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#13]
Oltre alle immagini, potrebbe essere utile inviare i log dell'esecuzione, la licenza dei dati, etc.

**Comment by spanezz** [comment]
Ora che c'è la directory `arkimapslib/static/` dove includere asset fissi che servono per tutti i rendering, si può creare al suo interno un `arkimapslib/static/tarball` il cui contenuto viene sempre copiato all'inizio della tarball in output.

Può andare come idea? Cosa ci mettiamo dentro?

**Comment by brancomat** [comment]
Sì, la licenza è un tema articolato, anche perché non è detto che la licenza dei dati in formato grib in input si trasferisca 1:1 ad un elaborato grafico derivato.
Provo a semplificare le casistiche:
- nel caso di elaborazione di file grib singoli le informazioni di licenza sarebbero comunque assenti a meno di non derivarle dalla tipologia di modello che sarebbe nel migliore dei casi un po' arbitrario
- nel caso di estrazione da arkimet il processo in corso è di standardizzare quello che già avviene in meteo-hub ovvero associare ad ogni dataset il campo `_license`, ad es, `_license = CCBY-SA4.0` ma questo implicherebbe o trovare un modo di fare arrivare questa informazione ad arkimaps o duplicarla in qualche forma.

Morale: io eviterei di includere informazioni di licenza nel pacchetto di uscita, demandandolo all'interfaccia di estrazione/frontend in cui è eventualmente integrato (come già avviene per meteohub, i postprocessamenti di fatto ereditano la licenza del dataset che è comunicata in fase di accesso al dataset).

**Comment by edigiacomo** [comment]
Mi piace! Facciamo che la chiudo e poi se torna l'esigenza la riapriamo.
