### ISSUE TITLE
serve caricare grib per generare le legende?

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#133]
_todo_: prendere uno script di render e togliere il passo `add_grib`

**Comment by edigiacomo** [comment]
Ho tolto il passo `add_grib` dalla ricetta per tp1h

```
 $ git diff
diff --git a/recipes/tiles/tp1h.yaml b/recipes/tiles/tp1h.yaml
index b6df0a8..776e94a 100644
--- a/recipes/tiles/tp1h.yaml
+++ b/recipes/tiles/tp1h.yaml
@@ -3,8 +3,8 @@ description: Total precipitation 01h
 recipe:
  - step: add_basemap
  - step: add_coastlines_bg
- - step: add_grib
-   grib: tpdec1h
+   # - step: add_grib
+   #   grib: tpdec1h
  - step: add_contour
    params:
     contour: "off"
```

 e ha generato tutte le mappe di precipitazione tranne quella per tp1h:

```
$ tar tf out.tar | grep legend
2022-11-30T00:00:00/tiles/tp6h_emro_tiles+legend.png
2022-11-30T00:00:00/tiles/tp3h_emro_tiles+legend.png
2022-11-30T00:00:00/tiles/tp24h_emro_tiles+legend.png
2022-11-30T00:00:00/tiles/tp12h_emro_tiles+legend.png

$ tar tf out.tar | grep png | cut -d/ -f 3 | cut -d+ -f1 | sort -u
tp12h_emro_tiles
tp24h_emro_tiles
tp3h_emro_tiles
tp6h_emro_tiles
```

**Comment by edigiacomo** [comment]
Tentativo numero 2 dopo telefonata con @spanezz - che è sempre troppo paziente con me :)

Ho modificato lo script Python generato da arkimaps, commentando sia la sezione `macro.mgrib` dalla funzione associata alla legenda che l'invocazione del rendering degli altri tile (si veda [renderer000.py.gz](https://github.com/ARPA-SIMC/arkimaps/files/10456054/renderer000.py.gz)).

```
$ python3 renderer000.py 
{"timings": {"import_magics": 308805160, "order4": 170366713}, "outputs": [["order4", "2022-11-30T00:00:00/tiles/tp12h_emro_tiles+legend.png", "b\"Magics-ERROR: ERROR: unable to open file '':  $oh\\xff\\x7f\\n\"\n"]]}
```

Ipotizzo che Magics si aspetti sempre un file e in questo caso la stringa associata al nome del file GRIB non sia allocata.

**Comment by spanezz** [comment]
Direi che la risposta a "serve caricare grib per generare le legende?" sia "purtroppo sí", e con questa possiamo chiudere l'issue
