### ISSUE TITLE
Rendering tile rettangolari

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#135]
Proviamo a vedere se magics renderizza anche tile rettangolari, così possamo ottimizzare il rendering dei bordi attorno alle macrotile. Per esempio, renderizzando una tile 8x2 invece di 4 tile 2x2

**Comment by spanezz** [comment]
Ho fatto una prova in [test.zip](https://github.com/ARPA-SIMC/arkimaps/files/10509802/test.zip) e sembra funzionare.

Provo a implementare rendering di tile rettangolari?

**Comment by brancomat** [comment]
ottimo, ok!

**Comment by spanezz** [comment]
Ho fatto push del prototipo sul branch `issue135`. Il tiling che fa non è il minimo possibile ma è una buona approssimazione, e dovrebbe vedersi una riduzione dei tempi di calcolo almeno per aree non rettangolari

**Comment by brancomat** [comment]
ho fatto qualche test su cosmo_2I_ruc e c'è una riduzione dei tempi risicata (3%) ma c'era anche poco da ottimizzare nel senso che le tiles del dominio che restano scoperte dai quadrati 8x8 sono poche. C'è anche il vantaggio di ridurre ulteriormente gli effetti dello spezzettamento del vento, vado di merge in master
