### ISSUE TITLE
fallimento test dopo merge branch 126

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#136]
`AttributeError: 'Renderer' object has no attribute 'make_python_renderer'`

log completi: https://simc.arpae.it/moncic-ci/arkimaps/last/master/centos8/build.log

**Comment by brancomat** [comment]
Restano test falliti su rocky8:
`AttributeError: 'Renderer' object has no attribute 'make_python_renderer'`

log completi: https://simc.arpae.it/moncic-ci/arkimaps/last/master/centos8/build.log

**Comment by spanezz** [comment]
Tentativo di fix in a58cd012ea288d5020cb302b90be60eb4bc9e582

Aspetto il risultato prima di chiudere l'issue

**Comment by spanezz** [comment]
Verde! Chiudo
