### ISSUE TITLE
Possibile bounding box non corretto nel caso di tile

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#139]
Si veda https://github.com/ARPA-SIMC/meteotiles/issues/47.

In pratica, pare che il bounding box dichiarato non coincida con quello della mappa, ma sia un po' più piccolo (e quindi la mappa sborda). La verifica l'ho fatta nella issue di meteotiles, se servono altre prove sono a disposizione.

**Comment by spanezz** [comment]
In 84cef46199a6376dfa8e64971b3b7c2e455de916 ho cercato di riprodurre la cosa nella test suite, fallendo: sembra che le tile generate coprano effettivamente il dominio, e che le funzioni `num2deg` e `deg2num` facciano i conti corretti, almeno confrontando i valori con [questi](https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/#6/-5.45/44.06).

Mi puoi aiutare ad arrivare a un test case per riprodurre il problema?

**Comment by edigiacomo** [comment]
TL;DR: è legato a #91.

Di seguito quanto ho scritto man mano che facevo prove.

Ho fatto una seconda verifica, questa volta con qgis.

Ho creato due file `sw.geojson` e `ne.geoson`, che trovi in [bounds.zip](https://github.com/ARPA-SIMC/arkimaps/files/10742982/bounds.zip).

In qgis ho aggiunto questi due file come layer (`Layer -> Add Layer -> Add Vector Layer` e poi ho creato una XYZ connection con URL `http://meteotiles.metarpa/tiles/cosmo_2I/2023-02-15T00:00:00/t2m_ita_small_tiles+000/{z}/{x}/{y}.png` e impostando come min e max zoom 6 e 7). Ho anche aggiunto il layer XYZ di OSM, disponibile di default su qgis.

Il risultato è il seguente, che è analogo a ARPA-SIMC/meteotiles#47.

![image](https://user-images.githubusercontent.com/927277/219030679-4a8faacb-578a-4b1e-ba4b-7b377d6f03dd.png)

Sono tornato sull'interfaccia web (meteotiles) e ho attivato la visualizzazione della griglia:

![image](https://user-images.githubusercontent.com/927277/219040791-5a1e14f5-3466-437e-b00b-90c6ddea7180.png)
![image](https://user-images.githubusercontent.com/927277/219041946-4f1c9798-5f28-4697-b840-d28cda7f8faa.png)

Si nota come, in entrambi i casi, i due punti appartengono sempre al medesimo tile degli estremi del PNG renderizzato.

Credo che il problema sia quello della issue #91: il bounding box definito nel flavour viene usato per definire quali tile renderizzare e poi il tile viene renderizzato per intero. La cosa si può notare visualizzando un prodotto del modello `ifs_ita010`: il modello originale ha extent latlon `(34, 2) - (50, 20)` (disegnati qui sotto con punti verdi) e con il bbox `(38, 5) - (48, 20)` (punti rossi) del flavour viene fuori questa cosa:

![image](https://user-images.githubusercontent.com/927277/219043982-63724a3c-36e5-4592-8908-49375d8e4106.png)

Si può notare come a NE il punto verde sia fuori dal tile del punto rosso e la mappa sia tagliata proprio sul confine di quest'ultimo tile; a SW, invece, i due punti sono nel medesimo tile e quindi la mappa viene renderizzata fino a che ha dati, cioè fino al punto verde.

Considerando che su meteotiles volevo limitare la navigazione al bounding box complessivo, risolvendo #91 si avrebbe comunque lo stesso risultato, con la differenza che non si avrebbe l'impressione che l'interfaccia nasconda alcuni estremi del prodotto, che in realtà sono quelli (anche se non tutti) che il flavour vorrebbe escludere.

**Comment by edigiacomo** [comment]
Dopo conversazione telefonica con @spanezz (che ringrazio per l'aiuto e le considerazioni), abbiamo deciso di calcolare il bounding box lato client facendolo coincidere con il tile (e quindi rendendolo analogo a quanto prodotto da arkimaps). Quando #91 sarà risolta, si potrà tornare a usare il bounding box dichiarato nel file di metadati.

Segno questa come duplicato di #91 e la chiudo.
