### ISSUE TITLE
errori eccodes

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#140]
Provando a fare un `arkimaps dispatch --grib` di un GRIB2 (esempio: [wrf.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/10744403/wrf.tar.gz) ) si ottengono errori da eccodes:
```
ECCODES ERROR   :  Error in native_type indicatorOfTypeOfLevel : Key/value not found
ECCODES ERROR   :  unable to get indicatorOfTypeOfLevel as long (Key/value not found)
```

la chiave `indicatorOfTypeOfLevel` è una chiave grib1 che non è presente nei grib2, non ho capito pero perché sia l'unica a dare errore (e perché non accada viceversa visto che alcune chiavi grib2 non sono presenti nei grib1).

C'è modo di aggirare la cosa? Con le ricette attuali escono 5 errori di questo tipo per ogni messaggio grib e la cosa sporca parecchio lo stderr

**Comment by spanezz** [comment]
è possibile sostituire `indicatorOfTypeOfLevel` con `levelType` nelle ricette? (magari con un sed brutale, per vedere di nascosto l'effetto che fa, tipo `sed -i -re 's/indicatorOfTypeOfLevel/levelType/g' `find recipes -name '*.yaml'`)

Da una rapida greppata sulle definition, sembra che levelType sia definito come alias sia per grib1 che per grib2

**Comment by brancomat** [comment]
confermo, non avevo visto, ottimo
