### ISSUE TITLE
problemi su dispatch grib wrf

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#142]
Ho un errore nel dispatch di una serie di grib (in allegato, un campione ridotto: [bruttogrib.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/10768961/bruttogrib.tar.gz) ):

```
$ arkimaps dispatch --grib t3 < test_data/brutto.grib 
Traceback (most recent call last):
  File "/usr/bin/arkimaps", line 467, in <module>
    main()
  File "/usr/bin/arkimaps", line 458, in main
    res = handler.run()
  File "/usr/bin/arkimaps", line 316, in run
    self.kitchen.pantry.fill()
  File "/usr/lib/python3.10/site-packages/arkimapslib/pantry.py", line 383, in fill
    self.read_grib(path)
  File "/usr/lib/python3.10/site-packages/arkimapslib/pantry.py", line 409, in read_grib
    self._parse_filter_output(line)
  File "/usr/lib/python3.10/site-packages/arkimapslib/pantry.py", line 400, in _parse_filter_output
    inp.add_instant(inputs.Instant(reftime, int(step)))
ValueError: invalid literal for int() with base 10: b'unavailable'
```

eccodes non mi dà errori ma un grib_ls dice che alcuni stepRange sono unavailable, che non so se sia un evento normale da gestire o un problema di codifica dei dati sorgenti (che è il motivo per cui la issue è assegnata anche a @dcesari )

**Comment by brancomat** [comment]
Ho circoscritto meglio il problema:
un dispatch con metadata arkimet non dava errori, il problema è nel filtro eccodes della tp per i grib2:
```
eccodes: centre != 98 and shortName is "tp" and editionNumber == 2
```

che faceva finire in `pantry` un grib codificato come tp ma senza nessuna indicazione di `step` o `endStep`: 
[tp_nostep.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/10773723/tp_nostep.tar.gz)

quindi in teoria in arkimaps si risolverebbe lato recipe trovando un modo di dire al filtro di ignorare i grib per cui mancano alcune chiavi (cosa che ancora non sono riuscito a fare, tristemente non trovo la sintassi), ma in generale:

@spanezz: quanto sarebbe complicato in questi casi far dare ad arkimaps qualche informazione sullo specifico messaggio che ha creato il problema? (in modo da non dover andare a caccia in caso di input consistsenti)

@dcesari: che cosa rappresenta quel grib? In generale gli unici che hanno quel tipo di problema nel pacchetto wrf sono un istante specifico di tp, uno di sdwe (snow depth water equivalent) e tutta la parte "10si" che credo sia la velocità del vento

**Comment by dcesari** [comment]
Immagino che quei grib servano a certe procedure che decumulano per avere un valore di riferimento (ovviamente == 0) all'istante zero da sottrarre al valore all'istante n, noi sicuramente non li usiamo. C'era qualcosa di simile anche in cosmo, con una precipitazione **istantanea** nulla all'istante zero, qui però sono codificati con il template dei dati cumulati ma con zero intervalli di cumulazione.

```
======================   SECTION_4 ( length=58, padding=12 )   =================
=====
1-4       section4Length = 58
5         numberOfSection = 4
6-7       NV = 0
8-9       productDefinitionTemplateNumber = 8 [Average, accumulation, extreme va
lues or other statistically processed values at a horizontal level or in a horiz
ontal layer in a continuous or non-continuous time interval (grib2/tables/2/4.0.
table) ]
...
42        numberOfTimeRange = 0
```

di norma `numberOfTimeRange = 1`. Riusciamo ad ignorarli senza troppe complicazioni?

**Comment by brancomat** [comment]
> Riusciamo ad ignorarli senza troppe complicazioni?

sì, in maniera empirica avevo trovato la raffinata sintassi:
```
! step is "unavailable"
```

ma verificare il parametro `numberOfTimeRange` mi pare più pulito.

**Comment by dcesari** [comment]
Ho controllato anche i parametri `10si` ma in questo caso non è chiaro, il parametro è velocità del vento, anche qui c'è il template max,min,med,cum con `numberOfTimeRange = 0` ma per tutti i possibili valori di `forecastTime` e i valori del campo sono non nulli. L'ipotesi più banale è che volessero essere i massimi del vento sull'ora precedente (raffica) ma per qualche motivo non siano riusciti bene, direi che ignoriamo anche questi, poi magari li segnaleremo a chi di dovere.

**Comment by dcesari** [comment]
Infine, per `sdwe` c'è sia la versione istantanea che quella cumulata con l'unavailable iniziale. Qui, guardando i valori max e min, mi pare di capire che quella istantanea è, correttamente, la quantità di neve che giace al suolo in quell'istante (in termini di massa d'acqua), mentre per la parte cumulata hanno abusato dello stesso parametro per indicare in realtà la precipitazione nevosa che cade nell'intervallo, che ha sicuramente un suo parametro a parte.
