### ISSUE TITLE
Schema validator per le ricette

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#146]
Facendo supporto a utenti che stanno scrivendo le loro prime ricette, mi sono scontrato con qualche messaggio di errore a runtime che potrebbe essere reso più user friendly attraverso la definizione di un validatore.

Ad esempio, se una ricetta non contiene il campo `arkimet`, l'errore restituito è

```
TypeError: Source.__init__() missing 1 required keyword-only argument: 'arkimet'
```

E vedendo il codice di `arkimapslib.inputs.Source` ipotizzo un errore analogo nel caso in cui manchi il campo `eccodes`.

Altri errori in cui sono incappato:

- Inconsistenze nei parametri per Magics: errore nella relazione tra le dimensioni degli array  `contour_shade_colour_list` e `contour_level_list` (il secondo dovrebbe essere generalmente uguale al primo + 1)
- Errori di sintassi nel campo `eccodes`

L'ho etichettata come "question" perché più che una issue è una domanda: avrebbe senso un validatore?

**Comment by brancomat** [comment]
Sarebbe molto utile!

**Comment by spanezz** [comment]
`arkimaps lint` dovrebbe fare quello che avete chiesto.

Al momento i controlli implementati sono:

* parametri non riconosciuti
* lunghezza di `contour_shade_colour_list` e `contour_level_list`
* sintassi delle formule di eccodes
* presenza di almeno uno di `arkimet` o `eccodes`

Si possono fare parecchi controlli in piú, per ora chiuderei questo ticket e aprirei ticket specifici man mano che trovate pattern magagne che sarebbe carino validare
