### ISSUE TITLE
ricette parziali (omissione di un filtro fra eccodes e arkimet)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#147]
Nella stesura di ricette sta emergendo che per alcuni prodotti specifici (tipicamente: output che gestiamo e gestiremo come grib nel prossimo futuro) dover redarre negli input delle ricette sempre sia la parte eccodes che quella arkimet è un po' oneroso.

Sarebbe bello poter specificare con una qualche sintassi sensata il fatto che un dato filtro non sia ancora stato compilato. Con @edigiacomo avevamo provato con una stringa tipo "not used" in arkimet ma questo poi genera un `ValueError` al primo tentativo di dispatch senza l'opzione `--grib`.

In alternativa un (brutto) workaround è decidere arbitrariamente due set di parametri  (uno per eccodes e uno per arkimet) talmente esotici da non essere mai usati ma mi sembra un poco improprio.

**Comment by spanezz** [comment]
andrebbe bene un "arkimet: skip" che ignora l'input se si sta facendo filtraggio con arkimet? (e la stessa cosa per eccodes)

**Comment by brancomat** [comment]
Benissimo!

**Comment by spanezz** [comment]
Ho fatto push dell'implementazione di `skip` su master: puoi provare se è quello che serve?
