### ISSUE TITLE
Caso d'uso: mappe su web pubblico di Arpae

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#148]
l web pubblico di Arpae prevede il caricamento delle mappe su un servizio REST basato su MongoDB (https://docs.python-eve.org/en/stable/). Di conseguenza, mappe e metadati devono essere caricati su documenti JSON. In particolare:

- Il bounding box delle mappe deve essere fornito con coordinate in WGS84
- La legenda deve essere fornita in formato JSON, sotto forma di lista di coppie nome e colore

Sono tutte informazioni che possono essere dedotte dalle ricette di arkimaps. È già adesso possibile parsare a mano i file YAML per ottenere queste informazioni, ma non mi pare banalissimo.

Una soluzione che mi viene in mente è quella di poter generare queste informazioni a partire dall'output di arkimaps, e.g. nel `process.json`.

**Comment by edigiacomo** [comment]
Una rettifica e una precisazione.

> Una soluzione che mi viene in mente è quella di poter generare queste informazioni a partire dall'output di arkimaps, e.g. nel `process.json`.

Intendevo il file `products.json`

La precisazione: le mappe sono PNG in EPSG:3857 "georeferenziabili" ad esempio quelle della issue #74 .

**Comment by spanezz** [comment]
Mi sembra sensato, anche perché già con #74 arkimaps ha codice per georeferenziare le tile, e possiamo renderlo piú generico

**Comment by spanezz** [comment]
In teoria, fatto in a374a0a (branch dell'issue #74 ancora non mergiato).

In pratica, se si usano metatile la georeferenziazione al momento è la georeferenziazione della metatile, non delle singole tile. Release early, release often, magari questo è sufficiente per sbloccare il devel blocking piú immediato intanto che ritaglio anche la georeferenziazione

**Comment by spanezz** [comment]
Fatto push sul branch `issue74` anche del ritaglio del bounding box per georeferenziare le tile

**Comment by edigiacomo** [comment]
La issue doveva essere chiusa automaticamente con il merge della commit c307ddf255c30a4dd13a23c2beceb6d63adb2f1a nel master, non ho capito perché non ha funzionato.
