### ISSUE TITLE
`products.json` size changes

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#153]
After an upgrade from arkimaps 1.2-1 to 1.7-3 on the server hosting the production of tiles, the `products.json` size for each model has increased exponentially (about 1.4 Gb). This basically hangs the web interface that reads those files.

I'm still investigating the cause because older `produtcs.json` files aren't available anymore and I can't reproduce the previous situations yet since arkimaps 1.2-1 is not available anymore on copr repo and it should run on an older version of eccodes.

I'll update this issue as soon as I have more elements

**Comment by spanezz** [comment]
The guilty commit is 7e137771c5e52bff9fb939fb55168b70359bc114

It added georeferencing information, but it contains redundancies that make the size explode. I'll now try to debug it
