### ISSUE TITLE
Documentazione delle API Python per la lettura dell'output di arkimaps

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#159]
Come concordato (https://github.com/ARPA-SIMC/arkimaps/issues/149#issuecomment-1867373008), apro questa issue per la documentazione delle API per la lettura dell'output di arkimaps (PNG e metadati).

**Comment by spanezz** [comment]
Ho aggiunto sphinx e una documentazione iniziale in `reference/outputbundle`. Sphinx ha sempre generato tutte le classi cosí appiccicate?

Ho documentato outputbundle e tutti i membri delle classi significative, e ho aggiunto alla documentazione del modulo un link alle classi da cui partire per leggere un bundle.

Mi puoi dare feedback fino a qui su cosa può mancare?

**Comment by edigiacomo** [comment]
Prima di tutto, grazie!

> Sphinx ha sempre generato tutte le classi cosí appiccicate?

In effetti, guardando https://arpa-simc.github.io/dballe vedo che c'è più spazio, però è anche vero che la doc di dballe è stata compilata con Sphinx 2.2.2 e io ho compilato con Sphinx 5.3.0, quindi forse è cambiato qualcosa nel CSS.

> Mi puoi dare feedback fino a qui su cosa può mancare?

Secondo me va benissimo, anche se probabilmente l'unico modo per verificare sarà con l'uso. Aggiungere un esempio, che potrebbe essere https://github.com/ARPA-SIMC/arkimaps/issues/149#issuecomment-1866449426.

**Comment by edigiacomo** [comment]
Altra richiesta: replicherei quanto fatto per arkimet e dballe, creando uno script per fare l'upload della doc su github pages.

**Comment by spanezz** [comment]
Ho aggiunto l'esempio, dopo aver verificato che funzioni ancora

**Comment by spanezz** [comment]
https://arpa-simc.github.io/arkimaps/ è online. Ho aggiunto il tradizionale script `rebuild-gh-pages` aggiornandolo un pochino al 2024

**Comment by spanezz** [comment]
Ti chiederei di farci un giro, e se tutto torna per il momento chiudere il ticket (che non vuol dire che a ticket chiuso non si aggiungono piú pezzi alla documentazione)

**Comment by edigiacomo** [comment]
Perfetto, grazie mille!
