### ISSUE TITLE
Preprocessing della precipitazione: scumulazione e conversione

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#17]
COSMO ha la precipitazione in mm e cumulata da instante di riferimento (0-1, 0-2, 0-3, 0-72), mentre ECMWF ha la precipitazione in m e cumulata (mi pare) sul periodo (0-6, 6-12, ...). È necessario un preprocessing che calcoli la precipitazione sul periodo in mm.

**Comment by spanezz** [comment]
Per la scumulazione sembra che ci siamo. Per la somma di convettivo/precipitante/eccetera, apriamo un ticket separato, o se dipende da ricetta a ricetta, ne parliamo nei ticket delle singole ricette?

**Comment by brancomat** [comment]
Sì mi pare un tema ricetta-dipendente nel senso che anche se il tema dal punto di vista fisico è univoco, come poi viene declinato variabile per variabile e modello per modello ha una certa variabilità.
Chiudo issue.
