### ISSUE TITLE
test failed on epel8

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#174]
full log: https://simc.arpae.it/moncic-ci/arkimaps/last/master/rocky8/build.log

```
FAIL: test_dispatch (test_rh2m.TestRH2MERG5EccodesERG5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimaps/tests/test_rh2m.py", line 42, in test_dispatch
    self.fill_pantry(step=0)
  File "/root/rpmbuild/BUILD/arkimaps/arkimapslib/unittest.py", line 194, in fill_pantry
    self.assertIn(fn, os.listdir(self.kitchen.pantry.data_root))
AssertionError: 'erg5_rh2m_2021_1_10_0_0_0+0.grib' not found in ['grib_filter_rules']
```

The same test is filing on epel9 while succeding on fedora38

**Comment by spanezz** [comment]
This seems like a problem with eccodes or input rules:

```
$ arki-query --data '' testdata/rh2m/erg5_rh2m_2021_1_10_0_0_0+0.arkimet > issue174.grib
$ grib_ls -p shortName,level /tmp/z.grib 
…
shortName   level       
r           2          
$ monci run -w. epel8 grib_ls -p shortName,level issue174.grib
…
shortName   level       
avg_r       2          
```

At a first glance i'd say that `recipes/rh_inputs.yaml` needs changing for erg5 to also allow `shortName` of "avg_r". I don't know enough of the problem domain if that's a good solution or if that'd be hiding an underlying problem

**Comment by brancomat** [comment]
Thank you.
Apparently, the same product (in terms of parameter category/value) has a shorName of "r" for eccodes 2.23 and "avg_r" for eccodes 2.26.
As you suggested I'll change the `recipes/rh_inputs.yaml`, given the mostrly internal use of that model/product I'd say is a viable solution.
