### ISSUE TITLE
grib_scaling_factor doesn't seem to work for mslp

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#176]
same test data and commands of #175 

Test server available: `rocky8`

The combination of `grib_automatic_scaling: off` and `grib_scaling_factor` doesn't seem to work, varying the latter or setting to on `grib_automatic_scaling` always result in the same output:

![image](https://github.com/user-attachments/assets/5dc19f89-bbbe-4a5d-bfba-18be875f7e5d)

the underlying version of Magics hasn't change (v 4.14.2)

**Comment by spanezz** [comment]
After running the preview command you should find a python script called `<workdir>/renderers/renderer000.py`, and running that script regenerates the image.

I verified that changing the value in the recipe reflects in a change value in the generated renderer script.

It looks like something is wrong in the renderer script: could you have a look at it and see why it doesn't give you what you expect?

**Comment by spanezz** [comment]
Ok, found it. Checking the difference with the renderer script from 1.19-1, I can see:

Before:
```py
        parts.append(macro.mgrib(grib_automatic_scaling=False, grib_scaling_factor=0.01, grib_input_file_name='issue175/pantry/icon_mslp_2024_11_12_0_0_0+0.grib'))
```
after:
```py
        parts.append(macro.mgrib(params={'grib_automatic_scaling': False, 'grib_scaling_factor': 0.01}, grib='mslp', grib_input_file_name='issue175/pantry/icon_mslp_2024_11_12_0_0_0+0.grib'))
```

Note the extra `params=`, which shouldn't be there. I'll try to fix it
