### ISSUE TITLE
Rendering del vento e altre variabili simili

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#18]
Il vento è un caso a parte, in quanto si devono usare dei parametri specifici per mgrib (grib_wind_mode, grib_wind_position_1, grib_wind_position_2) e usare mwind invece di mcont. Stessa cosa per altre variabili analoghe, come la corrente del mare.

**Comment by brancomat** [comment]
È rimasta scoperta la questione della spazializzazione degli indicatori in base alla risoluzione (secondo commento) che però si è un po' persa, apro nuova issue più chiara sul tema
