### ISSUE TITLE
Rendering: precipitazione totale a 1h, 3h, 6h, 12h e 24h

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#23]
sigla: **tp** associata al periodo tipo **tp1h** **tp3h**...

variabili necessarie:
`GRIB1,98,128,228` (IFS-ECMWF)
`GRIB1,,2,61` (COSMO)

preprocessing:
 - riportare preci ECMWF in mm come da #17
 - cumulazione come da #17

**Comment by brancomat** [comment]
Purtroppo ho realizzato solo ora una complicazione:
operativamente i passi 1h, 3h, 6h, 12h hanno le mappe corrispondenti ad un output di libsim con `--comp-full-steps` (ovvero cumulate rispettivamente prodotte ogni 1-3-6-12 ore)
Le cumulate a 24h (e solo quelle) sono calcolate e visualizzate a intervalli triorari: 0-0, 3-3, 6-6 e così via

**Comment by dcesari** [comment]
Ti prevengo che una scumulazione preliminare su 3h + una cumulazione su 24h senza `--comp-full-steps` non sortisce l'effetto che potrebbe essere atteso, perché `--comp-full-steps` agisce solo sulla scumulazione (cumulazione per differenze) e non sulla cumulazione per aggregazione. Per cui se proprio s'ha da fare, l'unica è cumulare su 24h senza l'opzione e poi selezionare gli intervalli voluti.

**Comment by spanezz** [comment]
Specifico che per come è fatto arkimaps adesso, la scumulazione viene fatta chiamando vg6d_transform per ogni ricetta indipendentemente.

Quindi la ricetta a 24h ha la sua chiamata a vg6d_transform, la ricetta a 1h ha la sua, eccetera.

Non è un problema mettere `--comp-full-steps` su tutte tranne la 24h. Domanda: visto che viene chiamata per ogni ricetta indipendentemente, `--comp-full-steps` serve o fa del lavoro in piú?

**Comment by dcesari** [comment]
Ah, bene, allora se ogni cumulazione ha la sua ricetta si può fare relativamente facilmente. Il `--comp-full-steps` ci vuole negli altri casi per non avere le cumulate "dispari" tipo 1-4 2-5, etc., per 1h è ridondante, ma in generale non fa danno.

Per le 24h, ripensandoci, forse conviene filtrare a monte!? Tipo estrarre/filtrare solo le scadenze con timedef modulo 3?

**Comment by spanezz** [comment]
Intanto ho cambiato le ricette mettendo `step: 1` invece di `comp_step: "0 01"`, che da un lato è piú semplice e immediato, dall'altro ci permette di avere piú libertà a cambiare l'invocazione a `vg6d_transform` a seconda dello step.

Ho anche tolto `--comp-full-steps`. L'invocazione comunque è in `arkimapslib/inputs.py` sotto `Decumulate.preprocess`: potete guardare se cosí va bene per tutto o se serva modulare gli switchini?

**Comment by brancomat** [comment]
Direi tutto bene, mi pare che presenza o assenza di `--comp-full-steps` non impatti particolarmente a livello prestazionale.

Ho fatto qualche test copiando la ricetta per provare cumulate a vari intervalli: anche senza il `--comp-full-steps` gli endstep di tutte le cumulate seguono l'intervallo di cumulazione (ogni ora per 1h, ogni 3 per 3h, eccetera) che come si diceva sopra va benissimo per tutte tranne che per quella a 24h.

**Comment by spanezz** [comment]
In 85ab0f74bc0371392b44810a4a7b334d1c8d900a ho implementato l'uso di `--comp-full-steps` per tutti gli step di scumulazione tranne il 24h
