### ISSUE TITLE
Rendering: 2 metre relative humidity

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#27]
Preprocessing:
calcolata da: temperatura di rugiada, pressione al livello del mare e temperatura 2 metri

variabili IFS-ECMWF:
```
GRIB1,98,128,151
GRIB1,98,128,167
GRIB1,98,128,168
```

variabili COSMO:
```
GRIB1,,2,2
GRIB1,,2,11
GRIB1,,2,17
```

Questa verrebbe comoda con libsim tramite modulo alchimia:
```
vg6d_transform --output-variable-list=B13003 in.grb out.grb
```

Contouring:

```
"contour_shade": "on",
"contour_shade_method": "area_fill",
"contour_level_selection_type": "level_list",
"contour_shade_colour_method": "list",
"contour_level_list": [0, 20, 40, 60, 80, 90, 100],
"legend": "on",
"contour_highlight": "off",
"contour_label": "off",
"contour_hilo": "off",
"contour": "off",
"contour_shade_colour_list": [ "red", "orange", "yellow",
    "green", "cyan", "blue"]
```

**Comment by spanezz** [comment]
Ho fatto una grossa ristrutturazione per avere input multiprodotto. Ho usato questo caso come esempio, creando `recipes/rh2m.yaml` (quale sarebbe il nome corretto?)

Ho riorganizzato le cose in modo che gli input possono avere input a loro volta. Gli step disponibili vengono calcolati generando gli input derivati e guardando che step vengono fuori, cosí si possono avere trasformazioni tipo decumulazione che potenzialmente generano step diversi da quelli di input.

Gli input sono ora condivisi tra tutte le ricette, ed è possibile avere ricette che definiscono solo input comuni ad altre ricette. Trovate esempi in `cp_inputs.yaml` e `tp_inputs.yaml`.

Ho aggiunto un input derivato di tipo `vg6d_transform` che concatena i suoi input e li dà in pasto a `vg6d_transform` con opzioni arbitrarie definite nella ricetta.

Ve lo giro per commenti

**Comment by dcesari** [comment]
Scusate, a suo tempo mi era sfuggita, la pressione a livello del mare è inutile qua, si può eliminare dall'input, la relazione tra t/td e rh è una cosa magica che non dipende dalla densità dell'aria e quindi dalla pressione.

D'altra parte se la pressione fosse stata richiesta (lo sarebbe ad es. se volessi calcolare l'umidità specifica (kg[vapore]/kg[aria])) ci sarebbe voluta la pressione superficiale, non quella a livello del mare, + l'opzione `--rounding` di `v7d_transform` che fa credere che i livelli a 2m e superficiali siano la stessa cosa.

**Comment by brancomat** [comment]
Ho rimosso la pressione a livello del mare e testato la ricetta confrontandola con l'operativo, va bene.

> Ho usato questo caso come esempio, creando `recipes/rh2m.yaml` (quale sarebbe il nome corretto?)

`rh2m` va benissimo

> Ve lo giro per commenti

La logica mi piace, permette di riciclare definizioni esistenti per creare sottoprodotti.
L'unico neo è che si è persa l'informazione degli input nei file `.md` di documentazione (per risalire ad esempio alle chiavi grib delle variabili necessarie ad una data ricetta). Però mi pare un risvolto meramente di documentazione, sposto questo commento nella #8 e chiudo questa. (ovviamente @dcesari e @edigiacomo se avete osservazioni riaprite pure questa)
