### ISSUE TITLE
Rendering: Geopotenziale

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#35]
sigla : **z** associata ad un livello di pressione tipo **z500**, **z850**

variabili necessarie:
`GRIB1,98,128,156` (IFS-ECMWF) (preprocessing necessario, vedi nota)
`GRIB1,,2,6` (COSMO)
entrambe associate a level tipo `GRIB1,100,500` (livello di pressione, tipicamente 250, 500, 700, 850)

preprocessing:
solo per ECMWF la variabile che abbiamo non è il geopotenziale (m²/s²)  ma l'altezza del geopotenziale
cito:
> L'altezza del geopotenziale è il geopotenziale diviso per la costante di gravità 9.8066 m/s**2

In sostanza per riportarlo a geopotenziale l'altezza va moltiplicata per 9.8066 (ripeto, solo il parametro ECMWF)

Questa cosa è gestibile anche via libsim (vedi anche #39):
```
vg6d_transform --output-variable-list=B10008 in.grb out.grb
```

contouring (isolinee):
```
"contour": "on",
"contour_shade": "off",
"contour_level_selection_type": "interval,
"contour_interval": 4,
"contour_line_colour": "black",
"contour_line_thickness": 3,
"contour_highlight": "off",
"contour_label_height": 0.5,
"contour_label_frequency": 2,
"contour_label_blanking": "on",
"contour_label_colour: "navy",
"legend": "off"
```

**Comment by spanezz** [comment]
direi decisamente di abbandonare `grib_automatic_scaling` e rimanere sull'uso dei `grib_scaling_factor` che, se non mi son perso qualcosa, ora dovrebbe fare quello che ci aspettiamo?

**Comment by brancomat** [comment]
> * su ifs (altezza del geopotenziale) mi aspettavo di dover usare come scaling factor 0.098066 ma in realtà ottengo gli stessi risultati della grafica operativa usando 0.1

alla fine anche la grafica operativa usa uno scaling factor di 0.1, e che mettendolo a quella che dovrebbe essere la variabile giusta le mappe differiscono da quelle di ECMWF e MeteoAM, a questo punto chiudo issue (il plot è in linea col resto dei plot operativi) e approfondiamo internamente la questione.

`grib_automatic_scaling` è stato comunque disabilitato su entrambi i modelli-
