### ISSUE TITLE
Rendering: frazione nevosa a 3h, 6h, 12h, 24h

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#38]
Rapporto fra precipitazione totale e precipitazione nevosa su 4 soglie (25/50/75/100%)

Variabili:
a partire dagli input di `tp` (già definito) e `sf` (da definire in #24) si calcola la percentuale di `sf` in `tp` (`tp : sf = 100 : x`) da plottare con il contouring indicato sotto.

(nella procedura originale veniva scritto un grib temporaneo con la percentuale ma impropriamente codificata come se fossero mm di pioggia)

Contouring:
```
"contour_shade":"off"
"contour":"on"
"contour_level_selection_type": "interval"
"contour_line_colour": "red"
"contour_line_style":"dot"
"contour_line_thickness": 2
"contour_label_height": 0.40
"contour_highlight": "off"
"contour_label": "on"
"contour_min_level": 25.0
"contour_max_level": 100.0
"legend": "off"
"contour_interval": 25.
```

**Comment by spanezz** [comment]
Ora che #24 ha `sf` calcolato, direi che manchi solo il calcolo della percentuale.

Lo fa `vg6d_transform` o lo implemento in Python?

**Comment by spanezz** [comment]
In caso sia da implementare in Python, questa è un'idea per farlo:

Nuovo input derivato di tipo `ratio`.

Prende in `inputs:` due input e fa il primo diviso il secondo.

Nel grib risultante mette i metadati del primo dei suoi input.

Prende una chiave `grib_set` che contiene un dizionario chiave-valore, da passare a eccodes per settare chiavi nel GRIB risultante.

In questo modo si possono tenere area e step dal primo grib, e settare cose tipo il prodotto per il grib risultante.

**Comment by brancomat** [comment]
> Lo fa `vg6d_transform` o lo implemento in Python?

No, sarebbe da implementare.

La proposta di implementazione in python mi sembra ottima.

**Comment by spanezz** [comment]
Nome: `sffraction`

**Comment by spanezz** [comment]
Ho aggiunto un prototipo di ricetta per `sffraction`. Passo per review, e se tutto va bene creazione delle ricette a 6h, 12h, 24h

**Comment by brancomat** [comment]
Testato con questi dati:
https://drive.google.com/file/d/1uQqtqri9qbx_1Z6-TzzCdGFF7SRsbWsP/view?usp=sharing

L'errore è il seguente:
```
$ ./arkimaps preview t2 sffraction3h
Traceback (most recent call last):
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/./arkimaps", line 427, in <module>
    main()
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/./arkimaps", line 418, in main
    res = handler.run()
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/./arkimaps", line 354, in run
    order = self.kitchen.make_order(self.kitchen.recipes.get(name), flavour=flavour, step=step, reftime=reftime)
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/arkimapslib/kitchen.py", line 146, in make_order
    for o in flavour.make_orders(recipe, self.pantry):
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/arkimapslib/flavours.py", line 155, in make_orders
    output_instants = pantry.get_instants(input_name)
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/arkimapslib/pantry.py", line 176, in get_instants
    instants = inp.get_instants(self)
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/arkimapslib/inputs.py", line 365, in get_instants
    self.generate(pantry)
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/arkimapslib/inputs.py", line 785, in generate
    eval(self.expr_fn, values)
  File "sffraction3h.yaml", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (2537,) (66540,) 
```

**Comment by spanezz** [comment]
Ho trovato la causa. L'espressione `snowdec3h[snowdec3h != 0]` crea un array coi soli elementi diversi da zero.

In sffraction, l'espressione `sffraction = snowdec3h[snowdec3h != 0] * 100 / tpdec3h[tpdec3h != 0]`  può funzionare solo se entrambi gli array hanno lo stesso numero di zeri, e dà i risultati attesi solo se gli zeri sono negli stessi posti.

Questo credo non sia l'effetto desiderato :sweat_smile: 

Ora cerco di capire come esprimere in numpy l'effetto desiderato

**Comment by spanezz** [comment]
Propongo questo, che ha il vantaggio di non cambiare la dimensione dei grigliati:

```yaml
   expr: |
           snowdec3h[tpdec3h == 0] = 0
           tpdec3h[tpdec3h == 0] = 1
           sffraction = snowdec3h * 100 / tpdec3h
```

Le modifiche fatte agli array sono limitate all'esecuzione di questo passo di processing, e vengono salvate solo per l'array di destinazione (`sffraction` in questo caso).

Ho fatto push di questa modifica, dimmi come la vedi. Può essere che ci sia da andare a riguardare le altre formule dove viene usata questa funzionalità di numpy

**Comment by dcesari** [comment]
Confermo da parte mia la formula dovrebbe dare il risultato atteso.

Aggiungo solo che, per motivi di troncamento grib, potrebbe verificarsi anche `snowdec3h > tpdec3h` per una piccolissima frazione del valore. Se questo rischia di creare artifizi nella grafica, meglio prevedere un troncamento tra 0 e 100 (con le vecchie versioni di libsim la precipitazione decumulata poteva anche essere leggermente <0, ora non dovrebbe più succedere).

**Comment by spanezz** [comment]
So può aggiungere una riga in piú tipo:
```
sffraction[sffraction > 100] = 100
```
oppure, meglio:
```
sffraction.clip(0, 100, out=sffraction)
```

Vedi: https://numpy.org/doc/stable/reference/generated/numpy.clip.html

**Comment by brancomat** [comment]
Confermo da analisi spannometrica su una scadenza a caso del grib con i dati pre e post clip, il troncamento pare servire:
```
con clip:                                  senza clip:
#-READ ONLY- maximum = 100;               #-READ ONLY- maximum = 150;
#-READ ONLY- minimum = 0;                 #-READ ONLY- minimum = 0;
#-READ ONLY- average = 1.0717;            #-READ ONLY- average = 1.07691;
#-READ ONLY- standardDeviation = 10.0103; #-READ ONLY- standardDeviation = 10.0693;
```

**Comment by brancomat** [comment]
Per ridurre il rumore e replicare l'attuale regola per il calcolo della frazione nevosa è stato necessario inserire l'azzeramento delle percentuali riguardanti precipitazioni inferiori al mezzo millimetro:
```
    expr: |
            snowdec3h[tpdec3h <= 0.5] = 0
            tpdec3h[tpdec3h == 0] = 1
            sffraction3h = snowdec3h * 100 / tpdec3h
            sffraction3h.clip(0, 100, out=sffraction3h)
```

Il problema è che snowdec3h e tpdec3h possono arrivare in due gusti: ifs con la precipitazione in metri e cosmo in millimetri quindi quel `0.5` dev'essere condizionale al modello.
Con @spanezz  abbiamo provato l'approccio:
```
 sffraction3h:
  - model: cosmo
    type: expr
    inputs: [tpdec3h, snowdec3h]
    expr: |
            snowdec3h[tpdec3h <= 0.5] = 0
            tpdec3h[tpdec3h == 0] = 1
            sffraction3h = snowdec3h * 100 / tpdec3h
            sffraction3h.clip(0, 100, out=sffraction3h)
    grib_set:
      shortName: tp
  - model: ifs
    type: expr
    inputs: [tpdec3h, snowdec3h]
    expr: |
            snowdec3h[tpdec3h <= 0.0005] = 0
            tpdec3h[tpdec3h == 0] = 1
            sffraction3h = snowdec3h * 100 / tpdec3h
            sffraction3h.clip(0, 100, out=sffraction3h)
    grib_set:
      shortName: tp
```
ma il risultato è che calcola a prescindere dal modello sia un `cosmo_sffraction3h` che un `ifs_sffraction3h` e uno dei due è inutile e sbagliato.

Un'alternativa potrebbe essere normalizzare gli output di tutte le cumulate nevose e di precipitazione usando lo standard cosmo ma si introduce un overhead inutile per (al momento) quest'unico prodotto

**Comment by spanezz** [comment]
Ho aperto #114 per tracciare l'ultima modifica richiesta da un punto di vista piú generale

**Comment by spanezz** [comment]
Visto quanto viene replicata questa espressione, è meglio se portiamo l'algoritmo di sffraction dentro ad arkimaps come tipo di input specifico

**Comment by spanezz** [comment]
In f11fa98d4324caeac52ba71f120854ca735a7402 ho aggiunto la selezione del valore di soglia a seconda dell'unità di misura.

Al momento ho messo sempre 0.5: passo la palla a voi per scegliere i valori di soglia desiderati
