### ISSUE TITLE
Nomi dei file di output

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#42]
Al momento l'output di arkimaps ha struttura `ricetta/<ricetta>+<step>.png`.

Questo è stato frutto piú di casualità che di scelta. Apro ticket per decidere esplicitamente la cosa.

**Comment by spanezz** [comment]
In #51 abbiamo definito `prodotto_variante/prodotto+step.png`, con `step` a 3 cifre. Al momento è implementato cosí, e se va bene possiamo chiudere questo issue

**Comment by brancomat** [comment]
In teoria va bene, in pratica prima di chiudere issue aspetterei esiti della #77 perché se si introduce il supporto a più corse di forecast con reftime diversi c'è da capire come differenziare gli output.

Le strade percorribili potrebbero essere:
* `reftime/prodotto_variante/prodotto+step.png`
* `prodotto_variante/prodotto_reftime+step.png`

Mi sembrerebbe vagamente preferibile la prima soluzione.

**Comment by dcesari** [comment]
Anche a me a naso piace più la prima.
