### ISSUE TITLE
Aggiungere la possibilità di far query direttamente ad arkimet

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#44]
Fermo restando che l'uso di arkimaps principale sarà come postprocessatore di arkimet, può essere utile aggiungere un comando per saltare il dispatching dei dati in input, e querarli direttamente da un dataset arkimet

**Comment by brancomat** [comment]
La situazione dei subcommand è sia soddisfacente sia già abbastanza articolata per non complicarsi la vita ulteriormente integrando il parsing di arki-query (cosa che non ho capito se sia ancora sul piatto), anche perché poi introdurrebbe una dipendenza opaca da arkimet, io chiuderei la issue.
(ma @spanezz sentiti libero di ri-aprirla se lo ritieni necessario)
