### ISSUE TITLE
diversificazione tipologie di output

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#45]
Gli output di arkimaps potenzialmente potrebbero appartenere a un prodotto cartesiano di più macrocategorie:

parto dalla tipologia:

1. output georeferenziati/georeferenziabili destinati a visualizzazioni stile tiles o WMS su webserver
2. output statici

La prima categoria avrebbe bisogno di output privi di riferimenti cartografici e di bordi, e di una legenda isolata (e unica per tutte le scadenze).
La seconda categoria l'esatto opposto, con legenda montata insieme alla mappa e idealmente un titolo con la descrizione e la corsa + scadenza di riferimento.

Tutto ciò è intersecato con l'area di interesse dei plot che potrebbe essere customizzabile.

Queste cose sarebbero gestibili editando direttamente gli yaml delle ricette e moltiplicandole all'infinito ma sarebbe probabilmente preferibile avere:
- uno switch per output georeferenziabile o "statico" (termine improprio ma non mi viene altro)
- la possibilità di passare un bounding box opzionale

(assegno a @spanezz ma pingo anche @edigiacomo per parere)

**Comment by spanezz** [comment]
Parte di questo issue potrebbe ora essere gestita tramite flavour (#51), e parte probabilmente può aver necessità di implementare qualcosa di specifico per tile e livelli di zoom.

Quando si presenta l'esigenza di generare tile, apriamo magari un issue apposta?

**Comment by spanezz** [comment]
Abbiamo una prima implementazione dell'output a tile, che vi invito a provare: [ho scritto unit test, ma non l'ho fatto girare](https://www.donotquoteme.com/Beware-Of-Bugs-In-The-Above-Code-I-Have-Only-Proved-It-Correct-Not-Tried-It-Donald-Knuth.html).

Per generare output con tiling, si può aggiungere una voce `tile` al flavour, contenente:
            
* `zoom_min: Int = 3`: livello di zoom minimo
* `zoom_max: Int = 5`: livello di zoom massimo         
* `lat_min: Float`: latitudine minima 
* `lat_max: Float`: latitudine massima
* `lon_min: Float`: longitudine minima 
* `lon_max: Float`: longitudine massima

**Comment by spanezz** [comment]
(grazie a @edigiacomo per aver fatto buona parte del lavoro)

**Comment by brancomat** [comment]
grazie, ho fatto qualche esperimento con un flavour di test: https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/flavours/tiles.yaml

ma gli output escono con legende e altre robe che non ci dovrebbero essere quindi credo di non aver capito bene come debba essere strutturato rispetto ai vari step e in particolare ai parametri di `add_basemaps` (ovvero: se li devo specificare e quali, perché immagino che parametri tipo `subpage_lower_left_longitude` siano in qualche modo autogestiti nell'output, o sbaglio?)

**Comment by spanezz** [comment]
Direi che possiamo partire dai file .py generati per i vari prodotti e vedere quali passi di magics debbano essere cambiati

**Comment by brancomat** [comment]
Ho testato con un flavour minimale:
```
---
flavours:
 - name: emro_tiles
   tile:
     zoom_mix: 3
     zoom_max: 5
     lat_min: 43.4
     lat_max: 45.2
     lon_min: 9.0
     lon_max: 13.2
   steps:     
     add_user_boundaries:
       skip: yes
     add_geopoints:
       skip: yes
```
(senza i due skip finali dà errore `input None not found.`)

il risultato di una preview al di là dell'estetica non rispetta i boundaries:
![image](https://user-images.githubusercontent.com/13255425/147244357-ef4973f4-737c-4ab7-8411-f757f9d4d63f.png)

dei quali non c'è traccia neanche nel file python generato: [py.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/7769415/py.tar.gz)

**Comment by brancomat** [comment]
A seguito di interazioni via chat, issue apparentemente risolta. Nel caso emergessero altri problemi relativi all'output su tile aprirei issue nuova che questa mi pare già moderatamente articolata.
