### ISSUE TITLE
legenda

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#46]
Dove previsto (alcuni plot tipo isolinee e flag del vento hanno un `legend:off`) sarebbe utile sia a livello diagnostico che in caso di output a tile avere la legenda di riferimento, ad esempio in un file isolato unico per ogni ricetta.

**Comment by edigiacomo** [comment]
Si potrebbe prendere ispirazione da https://github.com/ecmwf/skinnywms/blob/309da2b75f4e16f04adbc51a292ebab9e428e8c6/skinnywms/plot/magics.py#L364

**Comment by brancomat** [comment]
Riferimenti vari:
https://confluence.ecmwf.int/display/MAGP/Contouring
https://confluence.ecmwf.int/display/MAGP/Legend
la chiave è il parametro `contour_legend_only` di mcont che permette di produrre la sola legenda. La cosa sarebbe necessaria per i soli flavour con parametro `tile:` settato.

Allego se serve per testare lo sviluppo qualche grib di t2m estratti con:
```
arki-query --inline "Reftime:=today 0:00;product:GRIB1,,2,11;level:GRIB1,105,2;timerange:GRIB1,0,0h or GRIB1,0,1h or GRIB1,0,2h" http://arkiope.metarpa:8090/dataset/cosmo_5M_ita > t2m.arkimet
```
[t2m.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/9889093/t2m.tar.gz)

la ricetta coinvolta è `t2m.yaml`, esempio di flavour per processing a tiles:
```
arkimaps process --output out.tar --flavours=ita_small_tiles < t2m.arkimet
```

**Comment by spanezz** [comment]
Ho fatto push del branch `issue46` con una prima bozza di generazione di legenda.

Solo per gli output tiled, ora genera un legend.png dentro la directory del prodotto, e fuori dalle directory z/x/y.

Nella workdir rimane come di consueto un file `legend.py` con il python che genera la legenda.

La legenda che genera mi sembra che NON sia quello che si sta cercando, però non sono in grado di barcamenarmi per magics per tirar fuori la cosa giusta.

Vi chiederei di fare un giro di dispatch+render per generare il `legend.py`, poi spippolare direttamente su quello fino a fargli generare quello che vi serve, e poi allegarlo qui in modo che io poi possa incorporarlo nel resto dell'impasto.

Vi va bene?

**Comment by brancomat** [comment]
Facendo altre prove, aggiungo che da quel che vedo empiricamente:

- settare `contour_legend_only` a `True` o `on` non ha effetto, ce l'ha invece settare `legend_only=True` (che non è documentato nella reference guide)
- i parametri in `macro.mlegend` da quel che capisco sono analoghi a quelli usati in `macro.mcont` e potrebbero essere trasferiti lì

non sono però ancora arrivato ad un output soddisfacente

**Comment by brancomat** [comment]
Ok, forse ci siamo:
![image](https://user-images.githubusercontent.com/13255425/202507129-e6fbbf8f-eb24-4cb7-908a-e03dcc7cb3c2.png)

Allego esempio con originale per confronto: 
[legend.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/10033753/legend.tar.gz)

Elementi salienti:
- aggiunta di macro `mmap`
- settare una width e una height (in cm perché boh) comuni sia a `mmap` che nei settaggi della legenda
- parametri aggiuntivi della legenda in `mcont`

mi sarebbe piaciuto riuscire a fare un trim più decente dei bordi ma non ce l'ho fatta.

@spanezz ti ripasso la palla, se ci sono cose poco chiare sentiamoci

**Comment by spanezz** [comment]
Ho integrato le modifiche di @brancomat e fatto push nel branch `issue46`.

Da me non viene il bordo nero, per qualche motivo ho avuto piú fortuna.

Potete assaggiare e dirmi come sta ora di sale?

**Comment by brancomat** [comment]
Possibile ottimizzazione: la legenda attualmente viene prodotta per ogni scadenza, basterebbe produrla solo per una scadenza.

**Comment by brancomat** [comment]
La legenda viene prodotta anche quando nella ricetta è impostato `legend:off`

**Comment by spanezz** [comment]
> La legenda viene prodotta anche quando nella ricetta è impostato `legend:off`

Ok. Se ho capito bene, ci sono ricette che girano a tile, ma per le quali non serve produrre la legenda.

Al momento, hanno `legend:off` in uno degli step. Però non posso usarlo come marker per disabilitare la generazione della legenda, perché quella è un informazione specifica per quello step in magics, e non mi dice molto sulla ricetta stessa. Per esempio, in [recipes/standalone/thetaePV.yaml](https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/standalone/thetaePV.yaml) ci sono due step, uno con `legend: off` e uno con `legend: on`.

Se serve, possiamo aggiungere un flag alle ricette che ne disabilita la legenda. Però se consideriamo il tempo di rendering di tutte le tile di una ricetta, mi vien da dire che avere qualche legenda renderizzata in piú non dovrebbe spostare piú di tanto il tempo di rendering, e che si potrebbe semplicemente ignorare la legenda nell'output.

Ha senso, o c'è qualcosa che non ho capito nell'esigenza dietro la richiesta?

**Comment by spanezz** [comment]
Intanto, visto che la generazione della legenda funziona manipolando uno step `add_contour` esistente, ho implementato di saltare la manipolazione degli step add_contour che hanno `legend: off`. Se tutti gli `add_contour` hanno `legend: off`, non viene generata la legenda.

Questa modalità di generazione della legenda mi sembra ok per un prototipo, e in futuro ragionerei di come mettere esplicitamente, nelle ricette che richiedono una legenda, gli step per generarla.

Al momento però, per rilasciare qualcosa di utile in tempi utili, mi terrei il prototipo organizzato cosí com'è

**Comment by spanezz** [comment]
Ora col lavoro a #124 c'è un campo `legend_info` nel summary JSON con le informazioni sulla legenda generata, che è null se non è stata generata una legenda, e dovrebbe essere possibile usarlo anche per questo scopo.

Mi sembra che tra il verificare se il file della legenda esiste e vedere se c'è `legend_info` nel json, dovrebbero essere coperte varie strategie per arrivare allo scopo

**Comment by brancomat** [comment]
Al momento le ricette con `legend: off` stanno producendo png di legenda e dando `legend_info` pieno.
Allego il file prodotto da un run di cosmo_5M_ita:  [products.json.txt](https://github.com/ARPA-SIMC/arkimaps/files/10216742/products.json.txt)

Vedi ad esempio `mslp` che è `defined_in "mslp.yaml"`: lo yaml ha `legend: off`, il json lo segna come presente. Idem per il geopotenziale (z250, z500, z700) (qui le ricette nel master sono in `/tiles/`, ma il discorso è analogo)

**Comment by spanezz** [comment]
Riprodotto in test suite

**Comment by spanezz** [comment]
Riprova ora?

**Comment by brancomat** [comment]
Pare risolto!
