### ISSUE TITLE
pubblicare documentazione

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#47]
la doc che esce da `./arkimaps --document-recipes` andrebbe pubblicata

**Comment by spanezz** [comment]
Finché pubblichiamo la documentazione semplicemente su github, direi che ci sia tutto.
 
In un futuro possiamo pensare a cosa piú evolute tipo generare rst invece di markdown e integrare la documentazione delle ricette in documentazione sphinx, tipo interlinkando gli step alla documentazione delle relative classi Python che li implementano.

Per il momento, l'esigenza di documentazione è gestita in modo soddisfacente, o c'è ancora qualcosa che manca?

**Comment by brancomat** [comment]
> Per il momento, l'esigenza di documentazione è gestita in modo soddisfacente, o c'è ancora qualcosa che manca?

Al momento fra doc pubblicata su github e pacchettizzata è soddisfacente, ho lasciato issue aperta perché volevo semplicemente spostare i file `.md` di doc delle ricette in una directory diversa da `recipes`
