### ISSUE TITLE
Generazione input intermedi tra il dispatch e il render

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#49]
Alcune ricette hanno bisogno di input intermedi (per esempio: scumulazione, u e v del vento, umidità relativa).

Invece di gestirne un preprocessing a livello di ricetta, possiamo introdurre un passo intermedio post-dispatch degli input, pre-render, in cui in base a cosa è arrivato dal modello si generano nuovi GRIB che vengono importati nella directory di lavoro assieme agli input del modello.

Le ricette potranno poi trovare anche quei grib tra i loro input, come se fossero usciti dal modello.

Questo va implemementato in due gusti: arkimet e eccodes, perché l'output di queste generazioni intermedie (probabilmente principalmente fatte con libsim) dovrà esserere importato nel dataset intermedio arkimet o rismistato con grib_filter

**Comment by spanezz** [comment]
Abbiamo tp1h, con la scumulazione!

Potete controllare se va bene?

**Comment by brancomat** [comment]
Va bene! Ho confrontato l'output (sia in versione eccodesfiltrata che arkimet) con quello operativo di cosmo_5M (ifs ha passi triorari quindi non posso testare)

**Comment by spanezz** [comment]
Direi che su questo ticket ci siamo, nel senso che il codice ora ha un punto in cui mettere preprocessing, regole nelle ricette per sceglierli, e tutto quanto.

Per le specifiche strategie di preprocessing per i vari casi, chiuderei questo issue e ne parlerei nei ticket delle singole ricette o dei singoli casi di preprocessing
