### ISSUE TITLE
Delega passi comuni al mixer

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#51]
Tutte le ricette hanno i passi `add_basemap`, `add_coastlines_bg`, `add_cosastlines_fg`, `add_grid`, `add_boundaries` che sono sempre quelli.

Possiamo delegarli al Mixer, e tenere nella ricetta solo le parti `add_grib` e `add_contour`.

Questo potrebbe permettere di parametrizzare il mixer in base alle esigenze in input, per generare o meno le parti sopra e sotto i dati

**Comment by brancomat** [comment]
Nella #50 ho definito due aree che potrebbero essere usate per implementare un qualche meccanismo di selezione (dopo le estenderò con altre aree direttamente nei sorgenti).

Ci sono alcune opzioni di `mcoast` usate per caricare file esterni tipo shapefile (`map_user_layer`) o geopoint (`geo_input_file_name`). Per poterle usare nelle recipes senza inchiavardarle ho fatto una modifica opinabile a `add_boundaries` (vedi 25c8fce).

Visto che anche queste opzioni semi-custom andrebbero poi a definire una tipologia di basemap (o meglio, di area) comunque a più ricette, si potrebbe pensare di creare un'ulteriore cartella di file yaml dedicata alla definizione di aree, e referenziare questi file dall'interno della ricetta.

Esempio:
`recipes/t2m.yaml` potrebbe contenere un:
```
areas:
 ita
 emro
```
che si potrebbe tradurre nel dare in pasto a `add_basemap`, `add_coastlines_bg`, `add_coastlines_fg`, `add_grid`, `add_boundaries` parametri contenuti in:
```
areas/ita.yaml
areas/emro.yaml
```

cambierebbe un po' la logica perché a quel punto la recipe dovrebbe ripetersi (a parità di dati di input) per il numero di aree indicate

**Comment by spanezz** [comment]
Proposta: fare yaml che possano definire parametri di default per vari passi di ricette. Poi se si passa come parametro a un arkimaps il nome di uno di quei file, vengono caricati quei default.

Questo permette poi di personalizzare sia mappe che potenzialmente altre cose

**Comment by spanezz** [comment]
Potrebe servire addirittura nello stesso run generare due set di prodotti ognuno con set di parametri di default diversi?

**Comment by brancomat** [comment]
> Proposta: fare yaml che possano definire parametri di default per vari passi di ricette. Poi se si passa come parametro a un arkimaps il nome di uno di quei file, vengono caricati quei default.

Ottimo! Forse separerei o renderei in qualche modo gerarchiche le directory con i vari yaml, perché iniziano ad essere tantini. Concettualmente, un settaggio di area comune a più plot è una roba diversa da una ricetta di plot (però se ho ben capito su questa distinzione arkimaps sarebbe agnostico)

> Potrebe servire addirittura nello stesso run generare due set di prodotti ognuno con set di parametri di default diversi?

Non sono sicuro di aver capito, diciamo che l'occorrenza più comune (in caso di png non georeferenziati) è definire più aree per la stessa tipologia di prodotto.
Poi il set di aree può variare leggermente da prodotto a prodotto e soprattutto da modello a modello ma impostare default diversi a seconda del prodotto credo che più che altro complicherebbe la vita.

**Comment by spanezz** [comment]
Da telefonata, abbiamo concluso che sia utile poter generare piú varianti dei prodotti nello stesso run, cosí si generano una volta sola i prodotti intermedi.

Per distinguere gli output, si diceva, dentro al tar, di metterli in directory `prodotto_variante/`

**Comment by spanezz** [comment]
In ad682c615ab75f6596f1ea48c3811bb4ac094879 abbiamo introdotto le varianti (che in questo periodo suona brutto), e per stare nella metafora cuciniera le ho chiamate "flavours".

Ho aggiunto un esempio in `flavours/default.yaml`, per dare i parametri comuni per le basemap. Ho tolto i parametri di basemap dalle ricette che avevano quelli lí, cosí ora vengono presi dal file yaml.

Vedo che ci sono ricette che specificano una basemap diversa: quelle, avendo un set di parametri dentro, non prendono default dai flavour. Possiamo sentirci per ragionare di quali esigenze rappresentino e come gestirle.

Manca ancora la selezione dei flavour da renderizzare

**Comment by brancomat** [comment]
Sto testando il tutto, dopo le modifiche alle recipes `litota3` e `litota3_nord` e `mslp' non sembra caricare più correttamente il contouring usando quello che è normalmente il default interno di Magics quando uno non lo specifica.

**Comment by spanezz** [comment]
Se non sono specificati parametri nel flavour e nella ricetta, a meno di bug dovrebbero venire usati i parametri di default definiti in `arkimapslib/steps.py`, e dovrebbe esserci per `AddContour`: `"contour_automatic_setting": "ecmwf"`.

Puoi mandarmi il file `.py` generato per uno dei prodotti che non fa quello che deve, che vediamo che parametri vengono effettivamente passati?

**Comment by brancomat** [comment]
Mi ero dimenticato di spulciare il `.py`, da lì son riuscito a correggere direttamente la cosa (`AddGrid` usava `mcont` e non `mcoast` come macro, andando credo a sostituire le ultime opzioni di contouring che riceveva)

**Comment by brancomat** [comment]
Casi d'uso da capire come integrare nei "flavours" (elenco qui poi magari scorporiamo in issue sensate):

1. lo stesso prodotto potrebbe essere plottato su aree diverse intese non unicamente come settaggi di `add_basemap` ma includendo aggiunta di shapefile/geopoint condizionali al bounding box, come è attualmente per `litota3` vs `litota3_nord` 
2. lo stesso prodotto potrebbe essere plottato o con un output completo di sfondo, cartografia, confini amministrativi oppure privo di tutto tranne che il campo da plottare (in caso di alimentazione prodotti web georeferenziati )
3. potrei voler plottare tutte le recipes su un'area, e poi solo un subset di recipes su un'area diversa

possibili soluzioni:
per 1 e 2 probabilmente basterebbe la possibilità di rendere condizionali alcuni passaggi, tipo: un plot "statico" aggiunge tutti i vari `add_coastlines_*`, `add_grid` e `add_boundaries` che vengono invece omessi in un plot per il web (caso 2) oppure un flavour "nord_ita" mi aggiunge gli shapefile del caso (caso 1)

il punto 3 è meno fondamentale e ho qualche dubbio, c'è caso che in quel caso sia comunque più pulita una doppia chiamata (prima chiamata con set di ricette a flavour default, seconda chiamata subset di ricette con altro flavour) soprattutto se devo integrarlo in qualche procedura che poi vada ad esempio a ridistribuire o rinominare gli output (dovrei comunque sapere a priori se esiste un rapporto arbitrario fra aree e prodotti)

(pingo @edigiacomo en passant nel caso abbia altre idee)

**Comment by spanezz** [comment]
Per il punto 2, ho aperto #65

**Comment by spanezz** [comment]
Per il punto 1, ho aperto #66

**Comment by spanezz** [comment]
Per il punto 3, potrebbe essere sensata l'idea di specificare in un flavour un qualche tipo di filtro, per dire "usando questo flavour genera solo questi prodotti, o genera tutti i prodotti tranne questi" ?

**Comment by brancomat** [comment]
> Per il punto 3, potrebbe essere sensata l'idea di specificare in un flavour un qualche tipo di filtro, per dire "usando questo flavour genera solo questi prodotti, o genera tutti i prodotti tranne questi" ?

la prima soluzione mi piace di più, magari che in assenza di filtri ti faccia tutti i prodotti, mentre se vuoi limitare gli output per quel flavour ti permetta di specificare una sorta di whitelist di ricette

**Comment by spanezz** [comment]
Ok! Ho aperto #67
