### ISSUE TITLE
Dati per la test suite

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#52]
In #48 on iniziato una test suite.

L'idea al momento è di avere un file .arkimet con gli input necessari per generare uno step di una ricetta, e scrivere un test che la genera per cosmo, per ifs, con arkimet, e con eccodes. Al momento l'ho fatto per `hcc`.

I dati in input sono però troppo grandi per essere committati in git. L'idea per il workaround sarebbe fare una tarball coi dati di test, e uploadarla all'interno dei dati di una release in github

**Comment by spanezz** [comment]
È possibile committare i grib minimali assieme ai sorgenti. Se non ci interessano i dati presenti nei grib, ma solo la selezione del grib giusto e l'esecuzione degli step, possiamo anche committare dei grib con la parte dati settata a un valore costante:

```
$ ls -la workdir-cosmo/pantry/cosmo_2d+0.grib
-rw-r--r-- 1 enrico enrico 335168 Mar 13  2021 workdir-cosmo/pantry/cosmo_2d+0.grib
$ grib_set -s values=0  workdir-cosmo/pantry/cosmo_2d+0.grib /tmp/test.grib
$ ls -la /tmp/test.grib
-rw-r--r-- 1 enrico enrico 120 Nov  3 14:14 /tmp/test.grib
```

Questo può essere un buon punto di partenza, e se ci saranno da testare situazioni particolari che dipendono dai dati, possiamo valutarli caso per caso.

Anche l'idea di scriptare la creazione di una test suite mi piace: ci penso.

**Comment by spanezz** [comment]
Ho fatto merge in master di issue52. Ora nel repository, in `testdata/`, dovrebbe esserci tutto il necessario per far girare i test, alla modica cifra di 136Kb.

Ho testato individualmente tutti i test case che usano quei dati, prima e dopo la minimizzazione, per vedere che la minimizzazione non li rompesse.

Ho provato a far girare i test in un checkout pulito, ma ho un test, che non dipende da quei dati, che mi manda in segfault eccodes, quindi non posso dire "da me va tutto", però è un problema che cercherei di risolvere a parte, senza bloccare il lavoro su questo issue.

Non chiudo quindi il bug, ma ve lo passo per review

**Comment by dcesari** [comment]
Non so se può servire, il comando di libsim:

```
vg6d_transform [--trans-mode=s] --trans-type=boxregrid --sub-type=average \
 --npx=4 --npy=4 \
 gribin gribout
```

trasforma un grib facendo la media su blocchi di 4x4 punti (ovviamente si possono usare altri valori), per cui può essere utile per ridurre la risoluzione e quindi le dimensioni di un messaggio senza ridurne significativamente l'area geografica e mantenendo un contenuto informativo ragionevole, nel caso serva avere dei numeri veri che occupano poco spazio.

**Comment by spanezz** [comment]
Grazie, ho aggiunto l'appunto nel sorgente di `minimize`, cosí se in futuro ce ne viene il bisogno, dovrebbe essere piú facile ritrovarlo

**Comment by spanezz** [comment]
La strada dell'azzerare i values dei grib sembra percorribile. Ho aggiunto al repo (al momento nel branch issue52) uno script `testdata/minimize` che prende un file uscito da `arki-query --inline` e sostituisce tutti i valori nei dati dei grib che contiene con degli zeri.

`minimize` richiede arkimet a partire da [questo commit](https://github.com/ARPA-SIMC/arkimet/commit/30be1cf8f9b4a91c32c44f405a6195c23019fc41) che ho dovuto fare per l'occasione.

ecCodes, in codifica, si accorge che i dati hanno un valore costante e li rappresenta di conseguenza, occupando pochissimo spazio.

Ho provato a lanciare minimize sui dati del test di una ricetta, e i test continuano a passare. A questo punto, per i test dove questa è una via percorribile, provo a percorrerla e inizio a committare i dati minimizzati nel repository.

**Comment by spanezz** [comment]
A posteriori forse questo non stupirà nessuno, però non ci avevo pensato: quando i dati hanno valori costanti, i test ci mettono di meno a girare:

```
$ time eatmydata nose2-3 --fail-fast tests.test_lcc
....
----------------------------------------------------------------------
Ran 4 tests in 16.885s

OK

real	0m17.218s
user	0m29.963s
sys	0m0.394s

$ testdata/minimize testdata/lcc/* --verbose
2021-11-03 17:42:33 INFO minimize testdata/lcc/cosmo_lcc+12.arkimet:1: GRIB minimized: 335168b → 120b
2021-11-03 17:42:33 INFO minimize testdata/lcc/cosmo_lcc+12.arkimet: size went from 335372b to 322b
2021-11-03 17:42:33 INFO minimize testdata/lcc/ifs_lcc+12.arkimet:1: GRIB minimized: 29248b → 108b
2021-11-03 17:42:33 INFO minimize testdata/lcc/ifs_lcc+12.arkimet: size went from 29438b to 296b

$ time eatmydata nose2-3 --fail-fast tests.test_lcc
....
----------------------------------------------------------------------
Ran 4 tests in 9.647s

OK

real	0m9.979s
user	0m9.882s
sys	0m0.370s
```
