### ISSUE TITLE
dispatch di grib2 con filter=arkimet

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#56]
provando un dispatch di un grib2 ho un errorazzo:
```
$ ./arkimaps dispatch t1 < test_data/grib2_ifs.arkimet
{'type': 'timerange', 'style': 'Timedef', 'step_len': 3, 'step_unit': 1, 'stat_type': 0, 'stat_len': 3, 'stat_unit': 1}
Traceback (most recent call last):
  File "./arkimaps", line 365, in <module>
    main()
  File "./arkimaps", line 356, in main
    res = handler.run()
  File "./arkimaps", line 218, in run
    self.kitchen.pantry.fill(self.kitchen.recipes)
  File "/home/branco/git/arkimaps/arkimapslib/pantry.py", line 139, in fill
    dispatcher.read(infd)
  File "/home/branco/git/arkimaps/arkimapslib/pantry.py", line 178, in read
    arkimet.Metadata.read_bundle(infd, dest=self.dispatch)
  File "/home/branco/git/arkimaps/arkimapslib/pantry.py", line 154, in dispatch
    if trange['trange_type'] in (0, 1):
KeyError: 'trange_type'
```

Il problema è dovuto alla deduzione dalla scadenza dal tipo di timerange (dove si valuta se prendere `p1` o `p2` a seconda del `trange_type`. Nei GRIB 1 l'oggetto `trange` ha una struttura del genere:
```
{'type': 'timerange', 'style': 'GRIB1', 'trange_type': 0, 'unit': 1, 'p1': 64, 'p2': 0}
```

Nei GRIB2 (che allego [grib2_ifs.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/5933273/grib2_ifs.tar.gz) ) gli arriva una roba tipo:
```
{'type': 'timerange', 'style': 'Timedef', 'step_len': 3, 'step_unit': 1, 'stat_type': 0, 'stat_len': 3, 'stat_unit': 1}
```

ho provato a dare un occhio a `/etc/arkimet/scan/grib2.py` ma sono un poco arrugginito e non ho capito quale sia il campo giusto da considerare.
Un `--summary-short` dei dati produce questo output:
```
  Timerange:
    Timedef(3h, 0, 3h)
    Timedef(3h, 254, 0s)
    Timedef(6h, 0, 3h)
    Timedef(6h, 254, 0s)
    Timedef(9h, 0, 3h)
    Timedef(9h, 254, 0s)
    Timedef(12h, 0, 3h)
    Timedef(12h, 254, 0s)
    Timedef(15h, 0, 3h)
    Timedef(15h, 254, 0s)
```
Quindi suppongo la risposta sia "il primo paramentro di Timedef" che mi sembra sia `step_len` ma potrei sbagliare

**Comment by dcesari** [comment]
Si, il bello di Timedef è che il primo parametro è in genere quella che il popolo vuole, siano esse cumulate o meno, mentre nello stile GRIB1 la tipica esigenze è "P2 se c'è, altrimenti P1".
Però, se non sbaglio, lo stile Timedef si può usare come chiave di query anche se il dato è indicizzato in stile GRIB1, non so se questo aiuta.

**Comment by spanezz** [comment]
> Però, se non sbaglio, lo stile Timedef si può usare come chiave di query anche se il dato è indicizzato in stile GRIB1, non so se questo aiuta.

Non sbagli: si può. Finora però in arkimaps nelle query arkimet filtravamo per prodotto, non per timedef, e il punto a cui si riferisce Daniele è dove smistiamo per step.

Direi che `timedef["step_len"]` sia un buon inizio, se `style` è `Timedef`

**Comment by brancomat** [comment]
ho pushato or ora tre ricette che usano quei GRIB2

**Comment by spanezz** [comment]
qual è lo stato di questo ticket? Le tre ricette funzionano, o serve ancora qualcosa? Nel caso, quali ricette sono?

**Comment by brancomat** [comment]
Lo stato è lo stesso del primo messaggio (il dispatch funziona solo con `--filter=eccodes` e non con arkimet), quello che servirebbe è farlo funzionare anche con `--filter=arkimet`

Le ricette in gioco sono: `litota3.yaml viwve.yaml viwvn.yaml`

Il file di test è quello allegato al primo messaggio

**Comment by spanezz** [comment]
Scusa ero stordito e mi ero perso le parti fondamentali del ticket
