### ISSUE TITLE
Permettere di organizzare le ricette in sottodirectory

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#63]
Visto che la directory delle ricette inizia a crescere, per facilitarne l'organizzazione possiamo far sí che le ricette vengano cercate nella directory e in tutte le sue sottodirectory.

Se una ricetta che genera un prodotto sta in una sottodirectory, anche il prodotto verrà generato in una sottodirectory all'interno del tar.

Per esempio, `t2m.yaml` genererà `t2m/t2m+012.png`, e `foo/t2m.yaml` genererà `foo/t2m/t2m+012.png`

**Comment by brancomat** [comment]
Ottimo.
Realisticamente (se si introduce la possibilità dei sotto-file di configurazione per area discussi nella #51) l'esigenza potrebbe essere di lasciare nella dir principale le ricette che contengono attuali prodotti e spostare in sottodirectory le configurazioni aggiuntive tipo appunto le aree, ma predisporre la possibilità di output in sottodirectory separate mi sembra buona idea
