### ISSUE TITLE
Input per test litota3_nord

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#64]
Per implementare #60, sto prendendo litota3_nord come esempio, e partendo dai suoi test.

Sono riuscito a trovare i suoi input nei dataset IFS, ma non in quelli COSMO: ci sono?

Mi manca anche`/tmp/puntiCitta.geo`, me lo potete fare avere?

**Comment by brancomat** [comment]
> Sono riuscito a trovare i suoi input nei dataset IFS, ma non in quelli COSMO: ci sono?

No, al momento mi pare che quei dati non ci siano in COSMO (salvo illuminazioni di @dcesari), ma in generale il discorso area nord addizionata di shapefile + capoluoghi di regione è applicabile a praticamente qualsiasi altro prodotto.

> Mi manca anche`/tmp/puntiCitta.geo`, me lo potete fare avere?

Allego quello e l'altro shapefile a cui si fa riferimento in quella ricetta: 
[geo.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/6090894/geo.tar.gz)

**Comment by dcesari** [comment]
No, Cosmo non produce quella variabile, ne ha un'altra (che noi non abbiamo mai attivato, in realtà) che si chiama Lightning Potential Index, ma è una cosa un po' diversa con unità di misura diverse e si trova poco sopra nella code table grib2.
A proposito, trattandosi di variabile grib2 standard, suggerisco di omettere il 98 in product, perché è valida potenzialmente per qualsiasi centro. Discorso simile, in generale, per la maggior parte dei prodotti in grib2 che eventualmente ricettiamo. Poi forse potrebbe essere il caso di aggiungere `timerange:Timedef,,0,3h` o equivalente (ammesso che sia davvero così, non ho sottomano un grib corrispondente) se vogliamo davvero litota3, visto che esiste anche su 1 o 6 ore a giudicare dalla doc citata nella ricetta.

**Comment by dcesari** [comment]
Ovviamente mi contraddico subito, viwve.yaml e viwvn.yaml sono in grib2 ma usano una tabella parametri locale `arkimet: product:GRIB2,98,192,162,71,5`, etc.

**Comment by spanezz** [comment]
Per me l'issue si può chiudere, l'ho lasciato aperto perché non so se ci sono da integrare le osservazioni di Davide
