### ISSUE TITLE
add_grib: name: sostituito con grib:

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#68]
Per liberare `name:`, che è molto generico, per usi futuri, ho cambiato `name:` in `grib:` nello step `add_grib`.

Ho sistemato tutte le ricette che ci sono su master, ma lo segnalo come issue per adeguare le ricette di altri branch

**Comment by brancomat** [comment]
il branch `ifs_grib2` lo considero in freeze, se avrò bisogno di aggiornare la procedura prima di una release ufficiale passerò all'attuale master che ora riesce a produrre gli stessi output
