### ISSUE TITLE
Segfault di Magics sul plot del vento

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#69]
Sul mio portatile (Magics 3.3.1-1) ho un segfault di magics se provo a disegnare il vento. Allego script e dati di test:
[wflags-segfault.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/6134909/wflags-segfault.tar.gz)

Su `otto.metarpa` (Magics 4.4.0) il rendering invece funziona.

Potete fare un giro con lo script di prova sui vari ambienti di produzione per valutare l'entità del problema?

**Comment by brancomat** [comment]
L'attuale ambiente di produzione è CentOS 8 / Magics 4.4.0, e confermo che lì lo script funziona correttamente.
Gli ambienti di produzione con versioni più vecchie di OS o di Magics sono in dismissione quindi non li considererei.

Discorso leggermente diverso per l'ambiente di sviluppo (Fedora 32 / Magics 4.5.1) dove il plot funziona ma il thinning factor sembra non funzionare ma mi pareva che la cosa fosse già stata segnalata a ECMWF (o comunque lo faremo una volta confermata la cosa con la 4.5.3 di Magics che pareva contenere alcune migliorie sul tema)

In generale mi pare di ricordare che forse a partire dalla versione 4.0.0 di Magics avessero scorporato la parte python in un pacchetto software a parte (https://pypi.org/project/Magics/), è possibile che l'implementazione delle API python nella versione 3 sia in qualche modo diverso.

Ai fini di arkimaps chiudero l'issue (se però hai altre osservazioni parliamone).
