### ISSUE TITLE
Abort di Magics su un altro test case semplice

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#71]
Ho creato una chroot Debian testing per lavorare su arkimaps come workaround a #69, e ora (`python3-magics++` 1.5.5, `Magics` 4.5.3-1) ho invece un Abort su un test che su stable andava.

Allego script e dati di test: [magics-crash.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/6151050/magics-crash.tar.gz)

Di nuovo, potete fare un giro con lo script di prova sui vari ambienti di produzione per valutare l'entità del problema?

**Comment by brancomat** [comment]
Questa volta il problema pare consistente:

Fedora 32, Magics-4.5.3-1.fc32.x86_64, sia python3-Magics-1.1.1-1.fc32.noarch che python3-Magics-1.5.6-1.fc32.noarch:
```
$ python3 magics-crash.py 
ecCodes assertion failed: `h' in /builddir/build/BUILD/eccodes-2.20.0-Source/src/grib_query.c:572
Annullato (core dump creato)
```

CentOS 8, Magics-4.4.0-1.el8.x86_64, python3-Magics-1.1.1-1.el8.noarch
```
$ python3 magics-crash.py 
ecCodes assertion failed: `h' in /builddir/build/BUILD/eccodes-2.18.0-Source/src/grib_query.c:572
Annullato (core dump creato)
```

Provando a cambiare pezzi di codice a caso, il problema è nel contouring (o meglio nella sua assenza), aggiungendone anche uno minimale tipo un:
```
parts.append(macro.mcont(contour = "off"))
```
l'errore sparisce.

Non so se sia tecnicamente un bug, nel senso che non mi è chiaro se sia legittimo usare una `mgrib` senza una `mcont`. Non ho trovato riferimenti espliciti, ma nel tutorial le introducono insieme: https://confluence.ecmwf.int/display/MAGP/A+Geographical+Map

Sicuramente l'errore non aiuta.

**Comment by spanezz** [comment]
Al momento la test suite sembra girare senza problemi: chiudiamo questo issue?

**Comment by brancomat** [comment]
D'accordo

**Comment by brancomat** [comment]
D'accordo
