### ISSUE TITLE
chiamate mcoast general_style forse inutili

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#73]
Appunto per futuri approfondimenti a mente più lucida:
analizzando il py risultante sulla t2m (vedi allegato [t2m.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/6214376/t2m.tar.gz)  ) vedo una serie di chiamate tipo quella della riga 14:
```
parts.append(macro.mcoast(map_coastline_general_style='boundaries'))
```
che mi aspetterei rimpiazzate dai parametri specificati nel flavour, che invece sembrano andare in aggiunta

Temo che questo peggiori le performance e in alcune casistiche mistiche tipo proiezione mercatore crea una sovrapposizione di linee di costa e confini amministrativi a bassa e alta risoluzione:
![image](https://user-images.githubusercontent.com/13255425/112692948-0d001780-8e80-11eb-86f0-0606b13acb60.png)

**Comment by brancomat** [comment]
Dopo ulteriori approfondimenti, provo a riassumere il problema:
in proiezione mercatore (e solo in quella, vedi flavour `nord`) le due chiamate mcoast che aggiungono un
`map_coastline_general_style="foreground"` e `map_coastline_general_style='boundaries'` per qualche motivo plottano le coastline e i confini amministrativi a bassa risoluzione.

Questo però sembrerebbe indicare un doppio plot inutile di confini amministrativi e linee di costa in `AddCoastlinesFg` e in `AddBoundaries`: nel file python risultante dalla preview (vedi allegato nel messaggio precedente) c'è una prima chiamata con il general_style e una seconda che riporta i parametri (passati via ricetta/flavour/default).

Sarei quindi per rimuovere quelle chiamate (in assenza di specifiche verrebbero comunque presi i default specificati qualche riga sopra, corretto?).
Al momento le ho commentate nella 20e4d5f con un riferimento alla issue, ti chiedo però un parere (poi se positivo possiamo togliere commenti e chiudere questa issue)

**Comment by spanezz** [comment]
Premetto che ho preso quelle macro da esempi di Magics, e non c'è una logica specifica nella loro scelta a parte un vigoroso cargo culting. Qualunque cosa vediamo che sia piú funzionale, possiamo cambiarla.

Credo che foreground e background fossero divisi per distinguere le parti di boundary che stanno sotto ai layer coi dati e quelle che stanno sopra. Tipo avere i gradienti delle precipitazioni che coprono la cartina, ma averci disegnate comunque sopra le linee di confine.

Mi sembra strano che Magics disegni cose con risoluzioni diverse a seconda se si parli di boundary o di foreground. Suggerirei di fare esperimenti a partire dal file Python autogenerato dal rendering, per vedere se ci siano delle differenze di opzioni significative nei vari passaggi, e se valga piú la pena togliere la distinzione tra background e foreground, o convincere quello che sta disegnando a bassa risoluzione a disegnare con la risoluzione di tutti gli altri

**Comment by brancomat** [comment]
Ok, allora ragionerei al contrario, lascio così la situazione (tolgo i commenti allo script) poi in caso di necessità si può fare un'analisi del file python autogenerato in modo da capire se ci siano chiamate ridondate o inutili.
