### ISSUE TITLE
errore su parsing di grib (--filter=eccodes)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#75]
parsando un file senza metadati arkimet, scoppia:
```
$ ./arkimaps process -o out.tar --filter=eccodes < t2m+48.grib 
no messages found in -
Traceback (most recent call last):
  File "/scratch/dbranchini/git/arkimaps/arkimapslib/pantry.py", line 196, in fill
    arkimet.Metadata.read_bundle(infd, dest=dispatch)
RuntimeError: metadata entry does not start with 'MD', '!D' or 'MG' (parsing file <stdin>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/dbranchini/git/arkimaps/./arkimaps", line 413, in <module>
    main()
  File "/scratch/dbranchini/git/arkimaps/./arkimaps", line 404, in main
    res = handler.run()
  File "/scratch/dbranchini/git/arkimaps/./arkimaps", line 351, in run
    self.kitchen.pantry.fill()
  File "/scratch/dbranchini/git/arkimaps/arkimapslib/pantry.py", line 201, in fill
    raise RuntimeError(f"grib_filter failed with return code {proc.returncode}")
RuntimeError: grib_filter failed with return code 1
```
grib allegato
[t2m+48.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/7236770/t2m%2B48.tar.gz)

**Comment by spanezz** [comment]
arkimaps si aspetta che l'input sia comunque fatto di metadati arkimet, perché era pensato per girare come postprocessatore per arkimet.

Se serve farlo girare su normali file grib, posso aggiungere un'opzione `--grib` che implica `--filter=eccodes` e si aspetta dei grib in input.

Procedo?

**Comment by brancomat** [comment]
Procedi! Grazie.

(per quel che mi ricordo, arkimaps nasce come postprocessatore ma fra i desiderata mi pare ci sia sempre stato che potesse interpretare grib fuori arkimet o più in generale che la possibilità di scaricare dati da arkimet fosse disaccoppiabile dal plottaggio, per casi d'uso in cui la dipendenza da arkimet sarebbe stato un requisito troppo oneroso tipo altri CF o catene esterne tipo CINECA)
