### ISSUE TITLE
supporto a plot vento wdir + ws

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#78]
Al momento tutti i plot del vento sono fatti da u+v, è però possibile che il vento arrivi anche con componenti diverse tipo velocità e direzione.

Questa cosa è prevista in magics ed è pilotata dal parametro `grib_wind_mode` di `mgrib` (vedi https://confluence.ecmwf.int/display/MAGP/Grib+Input) che di default è settato a `uv` e in caso di velocità e direzione va settato a `sd`)

Allego grib di test con vento espresso in velocità e direzione: [wind.grib.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/7296494/wind.grib.tar.gz))

Inizialmente pensavo di aggiungere dei parametri in fase di definizione di input a mgrib come avviene ad esempio in  [/recipes/mcc.yaml](../tree/master/recipes/mcc.yaml#L8) ma nel caso del vento non mi è chiarissimo dove farlo.

Ho fatto una prova (ora commentata) in [/recipes/wind_inputs.yaml](../tree/master/recipes/wind_inputs.yaml#L36) ma ha come effetto un:
```
AttributeError: 'str' object has no attribute 'items'
```
e non mi è chiaro se non è il posto giusto per quell'operazione o c'è qualche problema sotto al cofano.

**Comment by spanezz** [comment]
Prova con:
```
   mgrib:
     grib_wind_mode: sd
```

Quando dici "è però possibile che il vento arrivi anche con componenti diverse tipo velocità e direzione", quando succede? Ci sono modelli che lo producono cosí, o si parla di rendering di dati provenienti da cose che non sono modelli?

**Comment by brancomat** [comment]
grazie! così funziona (cioè, passo ad altri problemi, i dati sembrano scalati male, ma forse è un problema del grib, approfondisco)

> Quando dici "è però possibile che il vento arrivi anche con componenti diverse tipo velocità e direzione", quando succede? Ci sono modelli che lo producono cosí, o si parla di rendering di dati provenienti da cose che non sono modelli?

Qui pingo @dcesari, in questo caso specifico si tratta di dati provenienti da un'analisi ma ignoro se esista uno standard.
Ai fini di arkimaps però mi pare tutto gestibile tramite `wind_inputs.yaml` l'unica casistica potenzialmente problematica e se un modello un pacco dati arrivasse con entrambe le modalità di descrizione vento per lo stesso step, ma mi pare una casistica improbabile.

**Comment by brancomat** [comment]
Ulteriore tassello che mi era sfuggito: `mgrib` vuole le componenti del vento in ordine corretto (`u` poi `v` oppure `ws` poi `wdir`).
Questo ordinamento dovrebbe essere pilotato dalla ricetta (testato empiricamente invertendo l'ordine in  [/recipes/wind_inputs.yaml](../tree/master/recipes/wind_inputs.yaml)) quindi non c'è niente lato codice da fare, solo da tenerne conto.

(in teoria `mgrib` ha dei parametri tipo `grib_wind_position_1` che dovrebbero servire ad esplicitare se non sono in ordine ma non sono riuscito a farli funzionare, vedi https://confluence.ecmwf.int/display/MAGP/Grib+Input)

**Comment by spanezz** [comment]
Direi che ordinarli direttamente nella ricetta sia la cosa piú semplice.

Nota che YAML permette commenti (col cancelletto come in Python), e vale la pena aggiungere una nota sul fatto che l'ordine indicato sia significativo per l'elaborazione successiva

**Comment by dcesari** [comment]
> Qui pingo @dcesari, in questo caso specifico si tratta di dati provenienti da un'analisi ma ignoro se esista uno standard. Ai fini di arkimaps però mi pare tutto gestibile tramite `wind_inputs.yaml` l'unica casistica potenzialmente problematica e se un modello un pacco dati arrivasse con entrambe le modalità di descrizione vento per lo stesso step, ma mi pare una casistica improbabile.

Arrivo dopo la puzza, in teoria abbiamo gli strumenti per calcolare ws e wdir anche dai dati dei modelli, forse cosmo permette di produrli direttamente, quindi non possiamo escludere di avere grib modellistici con queste variabili, anche se non ha molto senso fare l'operazione se l'ingrediente di partenza è u e v. Insomma è un caso un po' esotico, ma non lo butterei via se è già supportato/abile.
