### ISSUE TITLE
documentazione prodotti

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#8]
Posto che per ogni prodotto apriremo issue dedicata, visti gli sforzi in campo sarebbe bello capitalizzarli arrivando ad una documentazione per ogni "ricetta" che potrebbe essere una roba tipo:

- stringa più o meno mnemonica che faccia da chiave primaria (magari derivata dagli attuali script operativi e dalla tassonomia infomet)
- breve descrizione
- campi grib necessari (products e levels, che potrebbero corrispondere con i campi di match dei json)
- contouring di riferimento
- preprocessing utilizzato (se necessario)

Viste le notorie difficoltà nell'aggiornare la documentazione e il fatto che queste informazioni (tranne la stringa della descrizione) alla fine della fiera saranno più o meno integrati nello script, sarebbe fattibile pensare di autogenerarla in qualche modo?

Diciamo che in generale la vedrei più utile come autogenerata e schematica rispetto a ultradettagliata ma da ricordarsi di aggiornarla a mano, soprattutto per gli incroci ricetta/stili/chiavi grib

**Comment by brancomat** [comment]
A seguito del refactoring per la #27 si è persa come informazione nei file `.md` la sezione `inputs` che permetteva di risalire ai dati necessari alla produzione di una particolare recipe (products/levels).
Sarebbe carino (a bassa priorità) ripristinarla.

**Comment by spanezz** [comment]
Ripristinata. Ora nel generare la documentazione risolve ricorsivamente gli input di una ricetta, e mostra tutti gli input, e gli input dei loro input, di cui ha bisogno

**Comment by brancomat** [comment]
Al momento la rigenerazione della doc sostituisce tutti quelli che erano i titoli con i vari step (es `add_coastlines_bg`) con  il nome della ricetta.

Forse vale la pena aspettare le varie evoluzioni della #51 (e magari pure #28 e #29) per ricontrollare il tutto?

**Comment by brancomat** [comment]
Documentazione ok al momento, apro nuova issue se emergono altre esigenze.
