### ISSUE TITLE
Fare dispatch solo degli input effettivamente usati dalle ricette

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#87]
Visto che un flavor può selezionare solo un sottoinsieme di ricette, passando il nome del flavor al dispatch è possibile velocizzare l'elaborazione evitando di salvare nella directory di lavoro tutti gli input che poi non verranno usati

**Comment by edigiacomo** [comment]
@spanezz @brancomat questa issue è stata affrontata e/o risolta? Scusate ma non ho ben presente il problema.

**Comment by brancomat** [comment]
È un enhancement non ancora implementato: il dispatch (la creazione di grib isolati per variabile/scadenza in pantry) al momento è basato sull'intero elenco di prodotti/ricette, quello che suggeriva @spanezz è di basare il dispatch sull'eventuale campo `recipes_filter` del flavour (che serve a selezionare un subset di ricette) in modo da velocizzare il dispatch in questi casi.

**Comment by spanezz** [comment]
Fatto push! Ho fatto un flavour `issue87` copiato da `default` con l'aggiunta di `recipes_filter: [sf3h]`, e poi ho fatto dispatch del file di icon di #157, usando `--flavours=issue87`: il dispatch è molto piú rapido, perché vengono tenuti solo gli input sulla neve.

Vi chiederei di farci un giro
