### ISSUE TITLE
differenziare plot per reftime

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#88]
Al momento tutti gli input vengono collassati su un unico reftime buttando e segnalando con un warning gli step doppi.

Come discusso anche in https://github.com/ARPA-SIMC/arkimaps/issues/77#issuecomment-965072602 sarebbe bello poter dare più corse in pasto ad arkimaps, possibilmente con gli output strutturati come da proposta nella #42 (spoiler alert: `reftime/prodotto_variante/prodotto+step.png`)

**Comment by spanezz** [comment]
Quello che prima arkimaps considerava 'step' (nel senso di step del modello) ora è diventato 'instant', che include reftime e step. Bonus: si perde l'ambiguità tra "step" del modello e "step" delle ricette.

I nomi dei file di cui viene fatto dispatch nella pantry ora contengono anche anno, mese, giorno, ora, minuto, secondo. Le varie componenti non hanno padding perché da quello che ho capito `grib_filter` non supporta padding e sono file generati da grib_filter, per cui ci si ritrovano file che contengono robe tipo `2021_1_10_7_3_15`. Penso che finché sia una convenzione non ambigua e che non vincola i nomi dei file in output, non sia un problema.

I nomi dei prodotti in output non sono definitivi: chiudo questo ticket e prendo in carico #42 per sistemarli come richiesto.

**Comment by dcesari** [comment]
> nomi dei file di cui viene fatto dispatch nella pantry ora contengono anche anno, mese, giorno, ora, minuto, secondo. Le varie componenti non hanno padding perché da quello che ho capito `grib_filter` non supporta padding e sono file generati da grib_filter, per cui ci si ritrovano file che contengono robe tipo `2021_1_10_7_3_15`. Penso che finché sia una convenzione non ambigua e che non vincola i nomi dei file in output, non sia un problema.

Spulciando tra i miei filtri, io per i tempi in genere uso le chiavi derivate precotte `[dataDate]` e `[dataTime]` (però senza secondi), che hanno numero di caratteri fisso, oppure ho trovato robe tipo:
```
write "prova_[indicatorOfParameter%03d].grb";
print [latitude%.5f];
```
che suppongo funzionino, hope this helps. Purtroppo pare non esserci un manuale completo di grib_filter bisogna barcamenarsi tra help, esercizi ai corsi ECMWF pubblicati e test empirici.

**Comment by spanezz** [comment]
@dcesari grazie! Ho provato (commit  57a1eccc6e12214fb2adbd10cdb79e9c4d7879e8 nel branch `pantry_names`) a usare `[year%04d][month%02d][day%02d][hour%02d][minute%02d][second%02d]` e mi esce `undefundefundefundefundefundef`.

Direi che possiamo lasciare quello brutto ma che funziona, e riferirci a 57a1eccc6e12214fb2adbd10cdb79e9c4d7879e8 per una versione piú elegante una volta che abbiamo piú chiaro il funzionamento di grib_filter
