### ISSUE TITLE
sintassi della modalità `preview`

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#89]
Conseguentemente alla #88 è cambiata la sintassi della modalità preview che non accetta più la sintassi `prod+step` (es.: `t2m+000`)

Non sono riuscito a capire se esista già una nuova sintassi (forse no, mi pare splitti ancora sul `+`) e quale sia

In cascata poi andranno aggiornati:
 * l'help della modalità `preview`
 * il readme del progetto

**Comment by spanezz** [comment]
Ho sistemato l'errore in modo che ora con `prod+step` funzioni.

Visto che `prod+step` non identifica piú univocamente un prodotto (potrebbero esserci `prod+step` a reftime diversi), al momento in caso di ambiguità sceglie il primo che gli capita.

Non vorrei aggiungere l'obbligatorietà di dover specificare sempre il reftime, perché l'invocazione diventerebbe molto lunga, tipo `arkimaps preview t2m_2021-12-07T12:00:00+12`, che mi sembra rovini la comodità di fare preview al volo mentre si lavora a delle ricette.

Faccio una proposta di possibile interfaccia, piú per far partire una discussione e sentire anche le vostre idee, e senza l'ambizione di pensare che possa essere la soluzione migliore:

* `arkimaps preview t2m`: fa rendering di t2m allo step piú piccolo disponibile. Se lo step piú piccolo è disponibile per piú reftime, prende il reftime minimo
* `arkimaps preview t2m+12`: fa rendering di t2m allo step +12. Se lo step +12 esiste su piú reftime, prende il reftime minimo
* `arkimaps preview -d '$REFTIME' t2m`: fa rendering di t2m al reftime dato dal `-d` e allo step minimo disponibile
* `arkimaps preview -d '$REFTIME' t2m+12`: fa rendering di t2m al reftime dato dal `-d` e allo step +12

La sintassi di `$REFTIME` potrebbe essere o quella del matcher di arkimet `"reftime:=$REFTIME"`, o in alternativa qualuque cosa vada bene a [dateutil.parser](https://dateutil.readthedocs.io/en/stable/parser.html), o in alternativa qualunque cosa vada bene a `date --date=$REFTIME`

**Comment by brancomat** [comment]
> Non vorrei aggiungere l'obbligatorietà di dover specificare sempre il reftime, perché l'invocazione diventerebbe molto lunga, tipo `arkimaps preview t2m_2021-12-07T12:00:00+12`, che mi sembra rovini la comodità di fare preview al volo mentre si lavora a delle ricette.

Condivido pienamente.

Sulla proposta: per me il caso d'uso della modalità `preview` è diagnostica o editing di ricette che viene tipicamente fatto un subset limitato di dati quindi il supporto a reftime multipli non lo vedo troppo necessario/prioritario.
Detto ciò la proposta andrebbe comunque benissimo (preserva e migliora l'uso immediato permettendo comunque di lavorare su reftime multipli)

**Comment by spanezz** [comment]
Dovrebbe esserci tutto, usando la sintassi del comando unix `date` per il parsing dei reftime
