### ISSUE TITLE
Rendering: umidità relativa + vento a 700,850,925 hPa

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#94]
Da implementare: calcolo umidità relativa a partire da umidità specifica (vedi file `rh_inputs.yaml` che è una bozza non funzionante).

Questa la procedura per il calcolo dell'umidità relativa in quota (disponibile dalla versione 7.0.1 di libsim - cito da mail di @dcesari):

```
# calcolo la pressione come variabile
vg6d_transform --comp-var-from-lev --trans-level-type=100 t_q_isobar.grib p_isobar.grib
# metto tutto insieme
cat t_q_isobar.grib p_isobar.grib > tutto_isobar.grib
# calcolo RH con alchimia
vg6d_transform --display --output-variable-list=B13003 tutto_isobar.grib rh_isobar.grib
```
qui `t_q_isobar.grib` è l'insieme delle variabili `t` e `q` allo stesso livello di pressione (ad esempio la `q700` definita in `rh_inputs.yaml` e la `t700` definita in `t_inputs.yaml`)

**Comment by spanezz** [comment]
Per riferimento, la ricetta è `rh2m.yaml`

**Comment by spanezz** [comment]
Sto partendo dai test, e sto cercando di scaricare i dati per erg5, che se ho capito bene non ha bisogno di questa postprocessazione. Questa query:
```
arki-query --data 'reftime:=…;product:GRIB2,00200,000,001,001,004,000;level:GRIB2S,103,003,0000001800' 
```
Su http://arkiope.metarpa:8090/dataset/erg5v2 non ha risultati, mentre su erg5v1 sí. Serve supportare diversamente le due versioni di erg5?

**Comment by spanezz** [comment]
`rh2m` deve diventare quindi `rh2m700`, `rh2m850`, `rh2m975`, giusto?

**Comment by spanezz** [comment]
Ci dovremmo essere: lo passo per verifica

**Comment by spanezz** [comment]
Segnalo questo push che ho appena fatto:
```
  rh700:
-  - model: cosmo
-    type: vg6d_transform
-    args: ["--output-variable-list=B13003"]
-    inputs: [t700, q700, p700]
-  - model: ifs
     type: vg6d_transform
     args: ["--output-variable-list=B13003"]
     inputs: [t700, q700, p700]
```

Se non ci sono differenze di processazione tra un modello e l'altro, si può omettere la distinzione.

Questo velocizza anche la processazione: se un dato in input fa match per entrambi i modelli (per esempio, `t700` ha la stessa regola di eccodes per cosmo e ifs), arkimaps trova regole di postprocessing distinte, e siccome entrambe hanno gli input soddisfatti, le esegue entrambe, facendo il calcolo due volte.

**Comment by brancomat** [comment]
Perfetto
