### ISSUE TITLE
"preview" non trova le ricette nelle sottocartelle

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#99]
Se provo a fare una preview delle ricette annidate nelle sottocartelle `tiles` e `standalone` non le trova.
Se però le copio nella root delle recipes, le trova.

**Comment by spanezz** [comment]
Ho provato: `arkimaps preview workdir-ifs standalone/wmaxw10` funziona, e `arkimaps preview workdir-ifs wmaxw10` non funziona.

In teoria posso cambiare l'implementazione per farlo funzionare solo col nome del file, e tenere la directory solo per definire il path di destinazione del prodotto, e organizzare le ricette.

Questo però apre una domanda piú generale: posso avere ricette distinte in directory diverse con lo stesso nome? Tipo potrei avere `standalone/wmax.yaml` e `tiles/wmax.yaml` che sono ricette diverse? Nel qual caso, identificare una ricetta solo per nome introdurrebbe delle ambiguità, e il nome di una ricetta deve includere anche il path.

Intanto che ci ragioniamo, si può usare il path completo per poter fare preview anche di ricette in sottodirectory

**Comment by brancomat** [comment]
Ah ok, per qualche motivo pensavo che parsasse tutte le ricette e quindi il parametro fosse più un nome prodotto che un nome file. A questo punto si potrebbe pure chiudere issue, l'unico dubbio e se si riesce in qualche modo a disambiguare la cosa (ad esempio nell'help della modalità `preview`.

> posso avere ricette distinte in directory diverse con lo stesso nome?
Io forzerei la risposta a "no" (e forse si potrebbero introdurre controlli in questo senso) anche perché (se non ricordo male) poi nell'output non fa queste distinzioni di path e ci troveremmo con prodotti sovrapposti.

**Comment by spanezz** [comment]
> Io forzerei la risposta a "no" (e forse si potrebbero introdurre controlli in questo senso) anche perché (se non ricordo male) poi nell'output non fa queste distinzioni di path e ci troveremmo con prodotti sovrapposti.

Nell'output ora dovrebbe fare distinzioni di path, e non dovrebbe sovrapporre i prodotti: c'è da decidere se è un bug o una feature

**Comment by brancomat** [comment]
Ho aggiunto al README una nota sulla necessità di esplicitare la sottocartella (se presente) nel product in modalità `preview`.
Mi sarebbe piaciuto condensare l'informazione anche nell'help ma non ho trovato una formula sufficientemente stringata per farlo, visto che comunque è essenzialmente un tool di debug chiudo issue.

> Nell'output ora dovrebbe fare distinzioni di path, e non dovrebbe sovrapporre i prodotti: c'è da decidere se è un bug o una feature

Per ora lascerei così, poi se emergono problemi apriamo issue ad hoc
